// lang-zh-hk.ts
export const LANG_ZH_HK_NAME = 'zh_hk';

export const LANG_ZH_HK_TRANS = {

  // login
  'user_id': '用戶編號',
  'user_name': '用戶名稱',
  'email': '電子郵件',
  'password': '密碼',
  'company_id': '公司編號',
  'login': '登入',
  'language': '語言',
  'register': '註冊',
  'forget_password': '忘記密碼',
  'disclaimer': '聲明',
  'disclaimer_message': '登錄即表示您同意聲明的條款。',
  'dont_have_account': '未有帳戶？',
  'click_here_create': '按此創建公司帳戶',
  'internal_login': '內部登入',
  'company_login': '公司登入',
  'use_another_account': '使用另一個帳戶',

  // register
  'company_full_name': '公司全名',
  'company_short_name': '公司簡稱',
  'required_to_fill_in': '需要填寫這格',
  'confirm_password': '重新輸入密碼',
  'invalid_email_address': '無效的郵件地址',
  'password_not_match': '密碼不相符',

  // setting
  'change_language': '更改語言',
  'change_language_alert': '你是否確定更換語言: @{}?',
  'optional': '選填',

  // timeout-box
  'timeout': '時間超過',
  'timeout_prompt': '繼續使用平台',
  'time_left': '剩餘時間',
  'second': '秒',
  'continue': '繼續',
  'leave': '離開',

  //notification
  'notifications': '通知',
  'cert_is_ready_hint': ': 證書已可下載',
  'download_certifications': '下載證書',
  'download_report': '下載報告',

  // toast
  'ready_to_download': '準備下載',
  'download': '下載',
  'download_input': '下載@{}',
  'downloading': '下載中',
  'download_error': '下載錯誤',
  'download_completed': '下載完成',
  'download_waiting_prompt': '請等候下載完成後才繼續',
  'unable_to_download': '無法下載',
  'error_occurred': '發生錯誤',
  'details': '詳細內容',

  // page-not-found
  'page_not_found': '找不到頁面',
  'page_not_exist': '您要查找的頁面不存在',
  'previous_page_prompt': '您可以點擊下面的按鈕返回上一頁',
  'back': '返回',
  'no_errors_found': '找不到錯誤',
  'close': '關閉',

  // page-no-permission
  'forbidden': '禁止',
  'access_denied': '拒絕訪問',
  'no_permission_content': '您無權訪問該頁面',

  // layout
  'scroll_top': '置頂',
  'grid_view': '網格顯示',
  'list_view': '列表顯示',

  // header
  'logout': '登出',
  'welcome': '歡迎',

  // dashboard
  'dashboard': '儀表板',
  'dashboard_statistics': '數據統計',
  'dashboard_all_course_statistics': '所有課程統計',
  'dashboard_user_count': '用戶人數',
  'dashboard_course_count': '課程數',
  'dashboard_login_count': '登入人數',
  'dashboard_devices': '裝置',
  'dashboard_likes': '點贊數',
  'dashboard_recommendations': '推薦數',
  'dashboard_completions': '完成課程數',
  'dashboard_enrollments': '報讀課程數',

  //department
  'department_id': "部門編號",
  'department_short_description': "描述 (短)",
  'department_long_description': "描述 (長)",
  "select_department": "選擇部門",
  "selected_department": "部門列表",
  'self_department': "此部門",

  // course-management
  'course_management': '課程管理',
  'online_courses': '線上課程',
  'offline_courses': '線下課程',

  // user-management
  'user_management': '用戶管理',
  'all_users': '全部用戶',

  // subject
  'subject': '學系',
  'create_subject': '新增學系',
  'edit_subject': '編輯學系',
  'delete_subject': '刪除學系',

  // theme
  'theme': '主題',
  'create_theme': '新增主題',
  'edit_theme': '編輯主題',
  'delete_theme': '刪除主題',

  // actions
  'create': '新增',
  'edit': '編輯',
  'delete': '刪除',
  'actions': '操作',
  'more_actions': '更多操作',
  'view': '檢視',
  'search': '搜尋',
  'searching': '搜尋中',
  'save_and_next': '儲存並繼續',
  'skip': '跳過',
  'drag_and_reorder': '拖動並重新排序',
  'no_data_available': '無資料',
  'select': '選擇',
  'item(s)': '項',
  'selected': '已選',
  'checkbox_selected': '已選擇',
  'please_remove': '請移除',

  // subject-edit
  'name': '名稱',
  'lang_cn_short': '简',
  'lang_hk_short': '繁',
  'lang_en_short': 'ENG',
  'lang_cn_long': '簡體中文',
  'lang_hk_long': '繁體中文',
  'lang_en_long': '英語',
  'save': '儲存',
  'reset': '重置',
  'cancel': '取消',
  'confirm_delete_prompt': '你是否確定要刪除此項？',
  'confirm_permanently_delete_prompt': '你是否確定要永久刪除此項？',

  // course-edit
  'course': '課程',
  'create_course': '新增課程',
  'edit_course': '編輯課程',
  'delete_course': '永久刪除課程',
  'cover_image': '封面圖片',
  'choose': '選擇',

  //excel
  'browse': '瀏覽',
  'select_file_with_appropriate_format': '請選取擁有適當格式的檔案',
  'download_excel_template': '下載Excel範本',
  'excel_template': 'Excel範本',
  'preview': '預覽',
  'import_excel': '導入Excel',
  'import_by_excel': '以Excel導入',
  'excel_format_incorrect': 'Excel格式不正確',
  'excel_content_error': 'Excel內容錯誤',
  'excel_sheet_name_must_be': 'Excel中的表名必須是',
  'excel_sheet_name_must_have': 'Excel中的表名必須有',
  'no_excel_content': '找不到Excel內容',
  'no_relevant_information': '沒有相關資料',
  'total': '總共',
  'items': '項',
  'upload_failed': '上傳失敗',
  'import_failed': '導入失敗',
  'remarks': "備註",
  'delete_remarks': '完成Excel後請刪除備註和範例',
  'fill_in_next_sheet': '請於"@{0}"頁填寫@{1}',
  'create_template': '新增"@{0}"Excel範本',

  //temp
  'entry_date': '入職日期',
  'account_expiry_date': '帳戶有效日期',
  'user': '用戶',
  'vocab': '詞彙',
  'quiz': '小測',
  'enrollment': '新增學員',

  // course
  'course_title_en': 'Event Name (English)',
  'course_title_zh_hk': 'Event Name (Traditional Chinese)',
  'course_title_zh_cn': 'Event Name (Simplified Chinese)',
  'event_code': 'Event Code',
  'course_confirm': 'Manager Confirmation (1-Yes, 0-No)',
  'public_quota': 'Seat Available',
  'enquiry_email': 'Enquiry Email',
  'course_format': 'Course completion report format (Training/ CPD Score)',
  'external_course_code': 'Course ID/ Course Code',
  'register_start_date': 'Enrollment Start Date (YYYY-MM-DD HH:mm)',
  'register_end_date': 'Enrollment Deadline (YYYY-MM-DD HH:mm)',
  'status': '狀態',

  // Lesson
  'lesson': '課堂',
  'lesson_content': '課堂內容',
  'order': 'Order',
  'lesson_title': 'Lesson Title',
  'lesson_start_date': 'Lesson Start Date (YYYY-MM-DD HH:mm)',
  'lesson_end_date': 'Lesson End Date (YYYY-MM-DD HH:mm)',
  'location': 'Location',
  'course_id': '課程編號',
  'lesson_id': '課堂編號',
  'lesson_info': '課堂資料',
  'lesson_material': '課堂教材',
  'lesson_and_materials': '課堂 & 教材',
  'edit_lesson': '編輯課堂',
  'delete_lesson': '永久刪除課堂',

  // Material
  'material': '教材',
  'view_material': '檢視教材',
  'add_material': '新增教材',
  'edit_material': '編輯教材',
  'delete_material': '永久刪除教材',
  'add_attachment': '新增檔案',
  'add_scorm': '新增SCORM',
  'add_link': '新增鏈接',
  'add_activity': '新增活動',
  'view_activity': '檢視活動',
  'edit_activity': '編輯活動',
  'attachment': '檔案',
  'activity': '活動',
  'link': '鏈接',
  'hyperlink': '鏈接',
  'scorm': 'Scorm',
  'completion_criteria': '完成標準',
  'completed_when_opened': '開啟後即完成',
  'read_pdf_to_first': '閱讀PDF至開頭',
  'read_pdf_to_last': '閱讀PDF至最後',
  'watch_video_to_first': '影片開始後',
  'watch_video_to_last': '影片結束前',
  'submit_activity': '提交活動',
  'Page': '頁',
  'page': '頁',
  'visible': '可見',
  'mark_visible': '標記為可見',
  'mark_invisible': '標記為不可見',
  'compulsory': '必修',
  'stream_pending': '等候轉換中',
  'stream_generating': '轉換中',
  'stream_done': '已完成',
  'stream_failed': '失敗',
  'store_attachment': '儲存檔案',
  'update_attachment_language': '更新檔案語言',
  'store_scorm': '儲存SCORM',
  'material_empty_file': '課堂材料中包含空的課堂檔案',
  'material_empty_link': '課堂材料中包含空的鏈接',
  'material_link_no_http': '鏈接必須包含"http"或"https"字眼',
  'others': '其他',
  'download_file': '下載檔案',
  'open_hyperlink': '開啟鏈結',
  'Second': '秒',
  'second_': '秒',
  'setting_completion_criteria': '設定完成標準',
  'lesson_files': '課堂檔案',
  'scorm_popup_block': '我們嘗試在新視窗打開SCORM，但彈出式視窗已被封鎖。請允許這網站的彈出式視窗',
  'preview_scorm': '預覽SCORM',
  'downloadable': '可下載',
  'non_downloadable': '不可下載',
  'set_as_downloadable': '設定為用戶可下載',
  'set_as_non_downloadable': '設定為用戶不可下載',


  // Activity
  'mcq': '選擇題',
  'keyword': '關鍵詞',
  'drawing': '繪圖',
  'open_ended': '開放式問題',
  'video': '影片',
  'audio': '音頻',
  'assignment': '作業',
  'activity_name': '活動名稱',
  'activity_intro': '活動簡介',
  'background_image': '背景圖片',
  'tag': '標籤',
  'add_tag': '新增標籤',
  'add_tag_hint': '不能多於6個標籤',
  'confirm_update_activity': '你是否確定更新此活動? 更改內容後，之前的所有資料將被清除。',

  // Scorm
  'version': '版本',
  'accepted_scorm_version': '僅接受Scorm版本1.2和2004',

  // Discussion
  'discussion': '討論',
  'topic': '主題',
  'topics': '主題',
  'start_discussion': '開始討論',
  'create_topic': '創建主題',
  'reply': '回覆',
  'like': '讚好',
  'unlike': '取消讚好',
  'delete_topic': '永久刪除討論主題',
  'confirm_delete_topic': '你是否確定要永久刪除此討論主題?',
  'delete_reply': '永久刪除回覆',
  'confirm_delete_reply': '你是否確定要永久刪除此回覆?',
  'edit_topic': '編輯討論主題',
  'edit_reply': '編輯回覆',
  'choose_topic': '選擇討論主題',
  'image_attachment': '圖片附件',
  'content': '內容',
  'pin_topic': '置頂討論主題',
  'unpin_topic': '取消置頂討論主題',
  'pin_reply': '置頂回覆',
  'unpin_reply': '取消置頂回覆',

  // Quiz
  'create_course_quiz': '創建課程小測',
  'create_lesson_quiz': '創建課堂小測',
  'edit_quiz': '編輯小測',
  'delete_quiz': '永久刪除小測',
  'quiz_title': '小測標題',
  'passing_mark': '合格題數',
  'need_time_limit': '需要限時',
  'time_limit': '限時',
  'random_select_questions': '隨機抽選題目',
  'number_of_questions': '抽選題數',
  'show': '顯示',
  'dont_display': '不顯示',
  'display_correct_answer': '作答後顯示正確答案',
  'display_answer_type': '顯示答案類型',
  'display_all_answer': '顯示所有答案',
  'display_wrong_only': '只顯示錯誤答案',
  'display_mc_remarks': '多選題選項顯示備註',
  'allow_redo': '允許重做',
  'allow': '允許',
  'not_allow': '不允許',
  'fail_requires_retake': '不合格需要重讀',
  'number_of_fails': '不合格次數',
  'total_number_of_question': '總題數',
  'new_mc_question': '新增多選題',
  'new_cloze_question': '新增填充題',
  'mc_question': '多選題題目',
  'cloze_question': '填充題題目',
  'max_choices': '最多選擇答案數目',
  'title': '標題',
  'question': '題目',
  'answer': '答案',
  'option': '選項',
  'new_question': '新增題目',
  'new_option': '新增選項',
  'correct_answer': '正確答案',
  'remark': '備註',
  'explanation': '解釋',
  'confirm_edit_quiz': '你是否確定要更改此小測？',
  'edit_quiz_hint': '有關小測的所有資料(包括已提交的資料)將會被重置',
  'confirm_delete_quiz': '你是否確定要永久刪除此小測？',
  'import_multiple_quizzes_error': '小測不可導入多於一個題庫',
  'quiz_no_questions': '小測沒有題目',
  'pass_mark_exceed_total': '合格題數不可多於題目數目',
  'no_random_question': '沒有抽選題數',
  'random_question_exceed_total': '抽選題數不可多於題目數目',
  'pass_mark_exceed_random': '合格題數不可多於抽選題數',
  'please_input_valid_value': '請輸入有效數值',
  'max_choices_error': '最多選擇答案數目不可少於1或正確答案數目及多於選項數目',
  'no_answers_error': '請選擇多選題的正確答案',
  'quiz_report': '小測報告',
  'download_quiz_report': '下載小測報告',
  'need_until_correct': '需要完全正確才能完成',
  'time': '時間',
  'pages': '頁',
  'show_video': '顯示影片',
  'hide_video': '隱藏影片',

  // Offline course
  'offlineCourse_courseEvent': '線下課程活動',

  // File Picker
  'select_file': '選擇檔案',
  'my_computer': '我的電腦',
  'internet': '互聯網',
  'drag_and_drop': '請將檔案拖放到此處',
  'or': '或',
  'upload_by_url_hint': '請輸入檔案的URL',
  'upload_by_google_hint': '透過Google Drive選取檔案',
  'connect_to_google_drive': '連結Google Drive',
  'select_more': '選取更多',
  'reselect': '重新挑選',
  'upload': '上傳',
  'clear': '清空',
  'type': '類型',
  'size': '大小',
  'file_not_found': '未能找到檔案',
  'only_accept_file_type': '只接受下列檔案類型：',
  'one_file_selected_only': '只可選擇一個檔案',
  'load_image_failed': '載入圖片失敗',
  'cropping_image': '裁剪圖像',
  'crop': '剪裁',
  'apply': '套用',
  'zoom_in': '放大',
  'zoom_out': '縮小',
  'rotate': '旋轉',
  'auto_padding': '自動填充',
  'remove_padding': '移除填充',
  'imageLimitHint': '只能上傳不多於@{}的圖片',
  'fileLimitHint': '只能上傳不多於@{}的檔案',
  'videoLimitHint': '只能上傳不多於@{}的影片',

  // course-view
  'course_and_lessons': '課程 & 課堂',
  'course_settings': '課程設定',
  'delete_course_hint': '你是否確定要永久刪除此課程？',
  'permission_settings': '權限設定',
  'compulsory_settings': '必修設定',
  'enrollment_status': '報讀情況',
  'course_quiz': '課程小測',
  'lesson_quiz': '課堂小測',
  'evaluation': '問卷',
  'course_certificate': '課程證書',
  'create_lesson': '新增課堂',
  'published': '已發佈',
  'unpublished': '未發佈',
  'confirm_unpublish_course': '你是否確定取消發佈此課程？',
  'confirm_publish_course': '你是否確定發佈此課程？',

  // Upload progress
  'upload_progress': '上傳進度',
  'minimize_window': '縮小視窗',
  'maximize_window': '放大視窗',
  'estimating_time': '正在預測剩餘時間...',
  'completed': '完成',
  'upload_succeed': '上傳成功',
  'pending': '待辦',

  // Upload progress
  'download_progress': "下載進度",
  'download_succeed': '下載成功',
  'download_failed': '下載失敗',

  // course-edit
  'description': '簡介',
  'twoFA': '兩步驟驗證',
  'yes': '是',
  'no': '不是',
  'continual_identity_auth': '連續身份認證',
  'biometric': '生物識別',
  'google_auth': 'Google Auth',
  'have': '有',
  'has': '有',
  'have_yes': '有',
  'have_no': '沒有',
  'course_duration': '課程時間',
  'mins_short': '分',
  'minutes': '分鐘',
  'seconds': '秒',
  'enabled': '已啟用',
  'disabled': '已停用',
  'multi_lang_missing_title_hint': '請填寫名稱',
  'multi_lang_missing_description_hint': '請填寫簡介',
  'multi_lang_missing_cover_hint': '請選擇封面圖片',
  'customize_image': '自訂圖片',
  'new': '新增',
  'change_image': '更改圖片',
  'course_point': '課程點數',
  'access_days_limit': '訪問日數限制',

  // user-list
  'add_user': '新增用戶',
  'department': '部門',
  'job_rank': '職級',
  'view_and_edit': '檢視 & 修改',
  'activated': '啟用中',
  'deactivated': '停用中',
  'item_per_page': '每頁:',
  'next_page': '下一頁',
  'previous_page': '上一頁',
  'activation_title': '用戶狀態更改',
  'activation_content': '是否確定更改以下用戶的狀態為',
  'restore': '恢復',
  'confirm': '確定',
  'icon': '頭像',
  'locked_status': '用戶狀態',
  'activate_user': '啟用已選擇用户',
  'deactivate_user': '終止已選擇用戶',
  'approve_user': '核准用戶',
  'approve_selected_user': '核准已選擇用戶',
  'reject_selected_user': '拒絕已選擇用戶',
  'cp_allocation': '課程點數分配',
  'current_cp': '現有課程點數',
  'cp_to_selected_users': '分配指定數目課程點數至已選擇用戶',
  'required_cp': '此轉移所需的課程點數',
  'remain_cp': '此轉移後剩餘的課程點數',
  'transfer_cp': '轉移課程點數',
  'cp_amount_min_error': '數值不可以少於1',
  'cp_amount_not_enough': '公司沒有足夠的課程點數',
  'select_dept': '選擇部門',
  'confirm_user_data': '確認您輸入的資料',

  //user-view
  'external_id': '用戶編號',
  'basic_info': '基本信息',
  'course_info': '課程信息',
  'permission_info': '權限信息',
  'user_title': '職級',
  'change_password_hint': '需要更改才輸入',
  'user_report': '用戶報告',
  'create_user': '新增用戶',
  'profile': '用戶信息',
  'compulsory_courses': '必修課程',
  'non-compulsory': '選修課程',
  'recommended': '推薦課程',
  'pass': '合格',
  'achievements': '成就',
  'user_course_data': '用戶課程數據',
  'completed_courses': '已完成課程',
  'in_progress_courses': '進行中課程',
  'valid_password_alert_msg': '請輸入有效密碼',

  //user-view-course-info
  'subject_title': '學系',
  'theme_title': '主題',
  'course_title': '課程名稱',
  'pivot_start_date': '開始時間',
  'completion_status': '完成情況',
  'pivot_end_date': '完成時間',
  'has_quiz': '小測',
  'not_yet_assessed': '不設小測',
  'no_assessment': '未考核',
  'certificate': '證書',

  //user-admin-list
  'add_admin': '新增管理員',
  'admin_permission': '管理員權限',
  'user_employed': '在職',
  'admin_user_list': '管理員列表',
  'create_user_admin': '新增管理員',
  'update_user_admin': '更新管理員',
  'role_title': '權限範本',
  'role_titles': '權限範本',
  'permission': '權限',
  'viewable_department_titles': '部門管理權限',
  'role_list': '權限範本列表',
  'create_role': '新增權限範本',
  'update_role': '更新權限範本',
  'new_role': '新權限範本',
  'delete_role': '永久刪除權限範本',
  'delete_role_hint': '你是否確定要永久刪除此權限範本？',
  'all_permissions': '所有權限',
  'role_name_incorrect': '請使用其他名稱',
  'role_name_letter_incorrect': '請使用字母、數字或空格',
  'admin_step1': '選擇用戶',
  'admin_step2': '添加權限範本',
  'admin_step3': '添加部門管理權限',
  'admin_update_step2': '更新權限範本',
  'admin_update_step3': '更新部門管理權限',
  'select_roles': '選擇權限範本',
  'admin_other_roles': '其他權限範本',
  'user_current_department': "所屬部門",

  //user-admin-role-table
  'User Management': '用戶管理',
  'Manage Reports': '報告管理',
  'Company Management': '公司管理',
  'Unit Management': '單位管理',
  'Login CMS': '可登入CMS',
  'Login Teacher website': '可登入面授平台',
  'Manage users': '監視用戶',
  'Admin permission': '管理員權限',
  'Department Management': '部門管理',
  'overall_course_report': '整體課程報告',
  'course_participation_report': '課程參與報告',
  'course_completion_report': '課程完成報告',
  'overall_user_report': '整體用戶報告',
  'user_individual_report': '用戶單獨報告',
  'overall_user_login_report': '整體用戶登入報告',
  'Push Notification': '推送通知',
  'Banner': '橫幅',
  'Highlight Management': '專區管理',
  'Highlight Topic Management': '專題管理',
  'Mock Exam': '模擬考試',
  'Discussion': '討論',
  'Learning Map': '學習地圖',
  'Course Certificate': '課程證書',
  'Vocabulary': '詞彙',
  'Offline Courses': '線下課程',
  'Material Library': '資源庫',
  'System Management': '系統管理',
  'Manage Units': '公司管理',
  'Manage Plans': '計劃管理',
  'Manage Products': '產品管理',
  'Trainer Management': '導師管理',

  // image-viewer
  'no_image_found': '找不到圖片',

  // Qti
  'qti_format': 'QTI格式',
  'about_qti': 'QTI簡介',
  'import_qti': '導入QTI',
  'import_by_qti_format': '以QTI格式導入小測',
  'download_qti': '下載QTI格式的小測',
  'accept_qti_version': '僅接受QTI版本2.0, 2.1, 2.2',
  'qtiQuiz': 'QTI小測',
  'qti_quiz': 'QTI小測',
  'add_qti_quiz': '新增QTI小測',
  'submit_quiz': '提交小測',
  'test_id': '小測編號',
  'store_qti_quiz': '儲存QTI小測',
  'download_qti_quiz': '下載QTI小測檔案',
  'preview_qti_quiz': '預覽QTI小測',
  'qti_intro': 'QTI簡介',
  'supported_version': '支援版本',
  'supported_question_type': '支援題型',
  'qti_quiz_tutorial': '製作QTI小測教學',
  'qti_intro_paragraph_1': 'IMS問題與測試互操作性規範（QTI）定義了表示評估內容和結果的標準格式，支持在創作和交付系統，存儲庫和其他學習管理系統之間交換此材料。 它允許編寫評估材料，並可以在多個系統上互換使用。 因此，它旨在促進系統之間的互操作性。',
  'qti_intro_paragraph_2': '該規範包括一個數據模型，該模型定義問題，評估和問題及評估結果的結構，以及XML數據綁定，該XML數據綁定實質上定義了用於交換問題和其他評估材料的語言。 XML綁定被廣泛用於在不同的創作工具之間以及由發佈者交換問題。 規範的評估和結果部分使用較少。',
  'support': '支援',
  'suggest': '建議',
  'question_type': '題型',
  'mobile': '輕觸式',
  'desktop': '電腦',
  'qti_more_detail': '欲知更多，請參考以下連結',
  'qti_structure_paragraph_1': '製作一個QTI小測，需要上傳一個.zip檔案的包裹，當中包含.xml格式的test, part, section, item，以及item所需的各種素材。起始檔案必需命名為index.xml，並必需包含assessmentTest的標籤，否則系統無法讀取。',

  // multi-lang-basic
  'primary_language': '主要語言',
  'update': '更新',

  // search-box
  'search_add': '新增項目',

  // course-setting
  'quiz_will_be_deleted': '小測將被刪除',
  'evaluation_will_be_deleted': '問卷將被刪除',
  'confirm_multi_delete': '你是否確定要刪除: @{}?',
  'delete_hint': '所有資料(包括已提交的資料)將會被刪除',

  // evaluation-edit
  'confirm_delete_evaluation': '你是否確定要刪除問卷?',
  'delete_evaluation': '刪除問卷',
  'confirm_edit_evaluation': '你是否確定要更改問卷內容？',
  'edit_evaluation_hint': '有關此問卷的所有資料(包括已提交的資料)將會被重置',
  'evaluation_title': '問卷標題',
  'import_template': '導入預設問題',
  'section_title': '章節標題',
  'delete_section': '刪除章節',
  'new_section': '新增章節',
  'score_question': '比分題題目',
  'lowest_display_text': '最低分顯示文字',
  'highest_display_text': '最高分顯示文字',
  'score_question_range': '分數範圍',
  'open_ended_question': '自由題目',
  'new_score_question': '新增比分題',
  'new_open_ended_question': '新增自由題',
  'evaluation_no_sections': '問卷沒有章節',
  'question_required': '至少需要一個問題',
  'options_required': '至少需要兩個選項',
  'edit_evaluation_template': '編輯默認問題',
  'create_evaluation_template': '新增默認問題',
  'save_template': '保存默認問題',
  'cancel_template': '取消默認問題',
  'delete_template': '刪除默認問題',
  'confirm_edit_evaluation_template': '你是否確定要更改默認問題內容?',
  'confirm_create_evaluation_template': '你是否確定要新增默認問題內容?',
  'confirm_delete_template': '你是否確定要刪除默認問題?',
  'confirm_cancel_edit_evaluation_template': '你是否確定要取消更改默認問題內容?',
  'confirm_cancel_create_evaluation_template': '你是否確定要取消新增默認問題內容?',
  'confirm_cancel_edit_evaluation': '你是否確定要取消更改問卷內容?',
  'save_succeed': '保存成功',

  // course-enrollment
  'course_enrolled_users': '已報讀用戶',
  'course_new_enrollment': '新增報讀用戶',
  'course_enroll_users': '課程報讀用戶',
  'start_time': '開始時間',
  'completion_time': '完成時間',
  'not_yet_completed': '尚未完成',
  'ok': '知道了',
  'reorder': '重新排序',
  'move_up': '向上移動',
  'move_down': '向下移動',
  'course_name': '課程名稱',
  'search_result': '搜尋結果',
  'clear_search_result': '清除搜尋結果',
  'total_num_result_text': '共@{} 項結果',
  'delete_enrolled_user_prompt': '你是否確定要刪除已報讀用戶?',
  'view_user': '檢視用戶',
  'expiry_date': '到期日',

  // mock-exam
  'mockexam': '模擬考試',
  'mockexam_management': '模擬考試管理',
  'create_mockexam': '新增模擬考試',
  'number_of_completions': '完成人數',
  'qualified_number': '合格人數',
  'average_score': '平均分',
  'edit_mockexam_confirm': '你是否確定要更改模擬考試？',
  'delete_mockexam_confirm': '你是否確定要刪除模擬考試',
  'delete_mockexam_hint': '有關此模擬考試的所有資料(包括已提交的資料)將會被刪除。',
  'publish_mockexam_confirm': '你是否確定發佈此模擬考試？',
  'unpublish_mockexam_confirm': '你是否確定取消發佈此模擬考試？',
  'cannot_edit_published_mockexam': '不能更改已發佈的模擬考試',
  'cannot_delete_published_mockexam': '不能刪除已發佈的模擬考試',
  'publish': '發佈',
  'section': '章節',
  'create_section': '新增章節',
  'required': '需要填寫',

  // question-bank
  'question_bank': '試題庫',
  'create_question_bank': '新增試題庫',
  'edit_question_bank_confirm': '你是否確定要更改試題庫？',
  'delete_question_bank_confirm': '你是否確定要刪除試題庫',
  'delete_question_bank_hint': '有關此試題庫的所有資料（包括模擬考試中已提交的資料）將會被刪除。',
  'import_multiple_question_bank_error': '不可導入多於一個試題庫',

  // download-excel-template-btn
  'excel_remarks_sample_sheet': '這是範例頁, 請於 @{} 頁填寫資料',

  // quiz-basic
  'import_quiz_template': '導入小測Excel範本',
  'excel_remarks_one_quiz': '此表格只允許導入一個小測, 請在 Title 中填寫相同的標題',
  'excel_remarks_mc_question': '如果這是選擇題, 請在 Answer 中填寫選項編號',
  'excel_remarks_fill_question': '如果這是填充題, 請在 Answer 中填寫正確答案並不需填寫 MC Option 欄',

  // question-bank
  'import_question_bank_template': '導入試題庫Excel範本',
  'excel_remarks_one_question_bank': '此表格只允許導入一個題庫, 請填寫相同的標題和簡介',
  'excel_remarks_mc_question_option': '請在 Answer 中填寫選項編號',
  'excel_remarks_same_question_bank': '如果問題在同一個題庫, 請填寫相同的題目和簡介',

  // banner
  'home_page': '首頁',
  'banner': '橫幅',
  'banners': '橫幅',
  'login_banners': '登入橫幅',
  'banner_management': '橫幅管理',
  'login_banner_management': '登入橫幅管理',
  'create_banner': '新增橫幅',
  'create_login_banner': '新增登入橫幅',
  'edit_banner': '編輯橫幅',
  'delete_banner': '刪除橫幅',
  'delete_banner_confirm': '你是否確定要刪除此橫幅?',
  'website_url': '網址',
  'banner_status': '狀態',
  'no_banner': '沒有橫幅',
  'reorder_confirm': '儲存排序?',

  // highlight
  'highlight_management': '專區管理',
  'highlight': '專區',
  'create_highlight': '新增專區',
  'edit_highlight': '編輯專區',
  'delete_highlight': '刪除橫幅專區',
  'create_highlight_topic': '新增專題',
  'edit_highlight_topic': '編輯專題',
  'delete_highlight_topic': '刪除專題',

  // course-view
  'leave_page_hint': '你是否確定要離開此頁面?',
  'leave_page_desc': '系統將不會儲存您所做的變更',

  //unit
  'unit_management': '單位管理',
  'create_unit': '新增單位',
  'update_unit': '更新單位',
  'unit_id': '單位編號',
  'new_unit': '新單位',
  'unit_list': '單位列表',
  'unit': '單位',
  'unit_info': '單位資料',
  'unit_user': '單位成員',
  'unit_admin': '單位管理員',
  'add_unit_user': '新增單位成員',
  'add_unit_admin': '新增單位管理員',
  'short_description': "描述 (短)",
  'long_description': "描述 (長)",
  'unit_missing_short_description': '請填寫描述 (短)',
  'unit_missing_long_description': '請填寫描述 (長)',
  'unit_delete_hint': '你是否確定要刪除此單位?',
  'unit_delete_admin_hint': '你是否確定要刪除這些單位管理員?',
  'approved': '已核准',
  'unit_approve_hint': '你是否確定核准此單位?',
  'unit_unapprove_hint': '你是否確定取消核准此單位?',
  'default_unit_not_editable': '不可以更改默認單位',

  //department
  'department_management': '部門管理',
  'department_name': '部門名稱',
  'department_parent_id': '上級部門編號',
  'department_parent_long_description': '上級部門名稱',
  'create_department': '新增部門',
  'update_department': '更新部門',
  'new_department': '新部門',
  'department_delete_hint': '你是否確定要刪除此部門?',
  'department_missing_external_id': '請填寫部門編號',
  'parent_department': '上级部門',
  'department_manager': '部門經理',
  'add_department_manager': '選擇部門經理',
  'add_department_parent': '選擇上級部門',
  'duplicated_department_external_id_hints': '部門編號已被使用，請輸入有效的部門編號',
  'department_cannot_delete_hint': '未能刪除此部門',
  'department_has_manager_hint': '部門經理',
  'department_has_children_hint': '子部門',

  //widget-table
  'filter_columns': '篩選欄列',

  // course-enrollment-dialog
  'select_user': '選擇用戶',
  'edit_list': '編輯列表',
  'next_step': '下一步',
  'previous_step': '返回',

  // course-compulsory
  'confirm_delete_selected_prompt': '你是否確定要刪除已選擇的項目?',
  'compulsory_due_date': '到期日',
  'compulsory_users': '必修用戶',
  'add_compulsory_users': '新增必修用戶',
  'compulsory_departments': '必修部門',
  'add_compulsory_departments': '新增必修部門',
  'import_user_template': '導入用戶Excel範本',

  'course_reminder': '課程提醒',
  'send_course_reminder': '發送課程提醒',
  'not_completed_users': '所有未完成課程的用戶',
  'course_compulsory_reminder': '系統將在完成日期的@{}天之前自動發送提醒',
  'sending': '發送中',
  'sent': '已發送',

  // user-abilities-setting
  'user_permission': '用戶權限',
  'admin_permission_settings': '管理員權限設定',

  // course-permission
  'default_permissions': '默認權限',
  'has_permission_list': '有權限列表',
  'no_permission_list': '沒有權限列表',
  'has_permission': '有權限',
  'no_permission': '沒有權限',
  'add_permissions': '新增權限',
  'cancel_permission': '取消權限',
  'change_default_permissions_propmt': '你是否確定要更改默認權限?',
  'cancel_permissions_propmt': '你是否確定要取消已選擇項目的權限?',
  'cancel_existing_permissions': '取消現有權限',
  'existing_permissions': '現有權限',
  'add_input': '新增@{}',
  'create_input': '新增@{}',
  'edit_input': '編輯@{}',
  'change_input': '更改@{}',
  'add_items': '新增項目',
  'select_item': '選擇項目',
  'select_job_rank': '選擇職級',
  'join_date': '入職日期',
  'selected_date': '已選擇日期',
  'from': '從',
  'to': '到',

  //trainer
  'trainer': '導師',
  'trainers': '導師',
  'trainer_managemnet': '導師管理',
  'create_trainer': '新增導師',
  'edit_trainer': '編輯導師',
  'remove_trainer': '移除導師身份',
  'trainer_description': '導師簡介',
  'remove_trainer_role_confirm': '你是否確定要移除用戶導師身份？',
  'avatar': '頭像',
  'add_trainer_description': '加入導師簡介',

  // product
  'product': '產品',
  'products': '產品',
  'product_management': '產品管理',
  'create_product': '新增產品',
  'edit_product': '編輯產品',
  'delete_product': '刪除產品',
  'view_product': '檢視產品',
  'duplicate_product': '複製產品',
  'seat': '座位',
  'storage': '儲存空間',
  'free': '免費',
  'user_shop': '用戶商店',
  'company_shop': '公司商店',
  'price': '價錢',
  'currency': '貨幣',
  'delete_product_confirm': '你是否確定要刪除此產品？',
  'activate_product_confirm': '你是否確定要啟用此產品？',
  'deactivate_product_confirm': '你是否確定要停用此產品？',
  'product_info': '產品資訊',
  'web_platform': '網頁平台',
  'ios_platform': 'iOS平台',
  'android_platform': 'Google Pay平台',
  'purchase': '購買',
  'purchase_product': '購買產品',

  // income report
  'income_report': '收入報告',
  'stripe_transaction': '經Stripe付款',
  'ios_transaction': '經iOS付款',
  'android_transaction': '經Android付款',
  'count': '數量',
  'amount': '金額',
  'stripe_processing_fee': 'Stripe交易手續費',
  'stripe_processing_fee_hint': '(基本: 3.4% + HK$2.35)',
  'ios_fee': 'iOS費用',
  'android_fee': 'Android費用',
  'final_net': '最終淨賺',
  'each': '每項',
  'cp_transaction': '使用課程點數付款',
  'cp_fee': '課程點數手續費',

  // transaction
  'income_records': '收入記錄',
  'date': '日期',
  'customer': '顧客',
  'fee': '費用',
  'net': '淨賺',
  'platform': '付費平台',
  'coupon': '優惠碼',
  'refund': '退款',
  'refund_type': '退款方式',
  'no_refund': '不退款',
  'refunded_by_hkd': '已以港幣退款',
  'refund_by_cp': '以課程點數退款',
  'refund_amount': '退款金額',
  'withdraw_resources': '收回資源',
  'ban_access_to_course': '禁止訪問課程',

  // system
  'system': '系統',
  'system_management': '系統管理',

  // user-abilities
  'all_course_permissions': '所有課程權限',
  'create_quiz': '新增小測',
  'view_quiz_report': '查看小測報告',
  'create_evaluation': '新增問卷',
  'view_evaluation_report': '查看問卷報告',
  'view_discussion': '檢視討論',
  'set_permissions': '設置權限',
  'remove_course_abilities_disabled_hint': '請於@{}級別移除此用戶的權限',
  'remove_course_abilities': '移除權限',
  'no_selected_permission_hint': '請至少選擇一項權限',
  'change_all_ability_hint': '請於管理員權限頁面更改權限',
  'view_only': '只可檢視',
  'editor': '可編輯',
  'save_course_abilities_prompt': '你是否確定要儲存管理員權限?',

  // evaluation
  'evaluation_report': '問卷報告',
  'download_evaluation_report': '下載問卷報告',
  'incorrect_content': '內容不正確',
  'settings': '設定',

  // reports
  'reports': '報告',
  'course_reports': '課程報告',
  'user_reports': '用戶報告',
  'system_data': '系統數據',
  'num_enrollment': '報讀人數',
  'num_finished_users': '完成人數',
  'course_hours': '課程學時 (小時)',
  'all_courses': '所有課程',
  'created_date': '創建日期',
  'updated_date': '更新日期',
  'num_lessons': '課堂數目',
  'assessment_method': '考核方式',
  'filter_course_report': '篩選課程報告',
  'all_courses_report': '整體課程報告',
  'all_users_report': '整體用戶報告',
  'department_report': '部門報告',
  'login_report': '用戶登入報告',
  'recommendation_report': '推薦報告',
  'course_report': '課程報告',
  'report_is_ready_hint': ' 已準備好下載。',

  'hr_status': 'HR狀態',
  'recommended_count': '被推薦課程數',
  'enrolled_courses_count': '報讀課程數',
  'completed_courses_count': '完成課程數',
  'passed_courses_count': '合格課程數',
  'likes_count': '點贊課程數',
  'user_expiry': '離職日期',
  'filter_user_report': '篩選用戶報告',
  'year': '年',
  'month': '月',
  'day': '日',

  // months
  'month_1': '一月',
  'month_2': '二月',
  'month_3': '三月',
  'month_4': '四月',
  'month_5': '五月',
  'month_6': '六月',
  'month_7': '七月',
  'month_8': '八月',
  'month_9': '九月',
  'month_10': '十月',
  'month_11': '十一月',
  'month_12': '十二月',

  'select_all': '選擇全部',
  'unselect_all': '取消選擇全部',
  'select_hint': '請選擇',
  'select_all_search_result': '選擇全部搜尋結果',
  'unselect_all_search_result': '取消選擇全部搜尋結果',
  'login_report_disabled_hint': '請選擇年和月',

  // Zoom Meeting
  'add_zoom_meeting': '新增Zoom會議',
  'edit_zoom_meeting': '編輯Zoom會議',
  'zoom_input_meeting': '輸入現有Zoom會議',
  'zoom_create_meeting': '創建新的Zoom會議',
  'zoom_meeting_title': '會議名稱',
  'zoom_meeting_description': '會議簡介',
  'zoom_meeting_id': '會議 ID',
  'zoom_meeting_start_date': '會議開始日期和時間',
  'zoom_duration': '會議時長',
  'zoom_password_hint': '最多 10 個字符',
  'view_zoom_meeting': '檢視Zoom會議',
  'open_zoom_meeting': '打開Zoom會議連結',
  'zoom_not_enabled': '不支持連接到 Zoom 帳戶。',
  'zoom_oauth_message_title': '需要Zoom賬號授權！',
  'zoom_oauth_message_content': '請完成彈出連結中的步驟，完成授權後點擊「確定」。',
  'Zoom Meeting': 'Zoom會議',
  'zoom_meeting': 'Zoom會議',
  'zoom_install_title': '連接您的 Zoom 帳戶',
  'zoom_install_first': '如果您希望將Zoom帳戶連接到iTrain，請點擊 ',
  'here': '這裡',
  'zoom_install_second': ' 完成授權。',
  'zoom_uninstall_first': '您可以隨時於',
  'zoom_uninstall_second': '取消連接。',
  'zoom_not_allowed_to_update': '此 Zoom 會議只能由其創建者(@{})編輯。 ',

  'no_subject': '沒有學系',
  'no_theme': '沒有主題',
  'no_course': '沒有課程',
  'no_lesson': '沒有課堂',

  // course-statistics
  'course_statistics': '課程數據',
  'course_creation_date': '課程創建日期',
  'last_update_time': '最後更新時間',
  'start_date': '開始日期',
  'end_date': '結束日期',
  'all': '全部',
  'this_month': '本月',
  'this_quarter': '本季',
  'this_year': '本年',

  'num_completion': '完成人數',
  'num_incompletion': '未完成人數',
  'overall_num_enrollment': '總報讀人數',
  'overall_num_completion': '總完成人數',

  // verify email
  'verification_code': '驗證碼',
  'verify': '驗證',
  'verify_email': '驗證你的電郵',
  'verify_email_hint': '我們剛剛通過您的電子郵件向您發送了驗證碼。',
  'verify_failed': '驗證碼不正確。',
  'verify_succeed': '驗證成功。',
  'dont_receive_code': '尚未接收到驗證碼？',
  'has_been_resent': '已重發，請檢查',
  'next_resend': '下次重發機會：',
  'resend': '重新發送',

  // company
  'company_management': '公司管理',
  'company_info': '公司資訊',
  'usage': '用量',

  // subscription
  'subscription': '訂閱',
  'subscription_info': '訂閱資訊',
  'current_plan': '當前計劃',
  'next_plan': '下個計劃',
  'plan_title': '計劃名稱',
  'plan_description': '計劃簡介',
  'period': '訂閱期',
  'paid_by': '付款人',
  'subscribe': '訂閱',
  'active': '服務生效中',
  'incomplete': '未完成付款',
  'incomplete_expired': '未完成付款並過期',
  'trialing': '試用中',
  'past_due': '過期',
  'canceled': '已取消',
  'unpaid': '未付款',
  'unsubscribe': '退訂',
  'resume_subscription': '恢復訂閱',
  'change_plan': '更換計劃',
  'unsubscribe_confirm': '您是否確定要退訂目前計劃？',
  'unsubscribe_succeeded': '已成功退訂',
  'resume_subscription_confirm': '您是否確定要恢復訂閱？',
  'resume_subscription_hint': '這動作會取消已預訂的計劃',
  'resume_subscription_succeeded': '恢復訂閱成功',
  'unsubscribed': '已退訂',
  'service_end_at': '服務終結日',
  'upgrade_now': '即時升級',
  'change_plan_period_end': '當前計劃結束後更換',
  'scheduling_next_plan': '安排下一個計劃',
  'next_plan_scheduled': '下一個計劃已安排',
  'subscription_change_and_charge_at': '您的訂閱會在這時間後自動更換計劃及收費',
  'cancel_scheduled_subscription': '取消預訂計劃',
  'cancel_scheduled_subscription_confirm': '您是否確定要取消預訂計劃？',
  'cancel_scheduled_subscription_succeeded': '已取消預訂計劃',

  // payment
  'add_payment_method': '新增付款方法',
  'cancel_payment': '取消付款',
  'card': '信用卡',
  'card_data': '信用卡資料',
  'card_number': '信用卡號碼',
  'charge_id': '收費編號：',
  'confirm_3ds': '驗證3D-Secure',
  'confirm_payment': '確認付款',
  'coupon_code': '優惠碼',
  'coupon_discount_less_hint': '優惠碼折扣少於 1 個課程點數。 此優惠碼無效。',
  'error_code': '錯誤碼',
  'failed': '失敗',
  'incomplete_cvc': '您的信用卡安全碼不完整。',
  'incomplete_expiry': '您的信用卡到期日不完整。',
  'incomplete_number': '您的信用卡號碼不完整。',
  'incomplete_payment': '未完成付款程序',
  'invalid_coupon': '優惠碼無效',
  'invalid_expiry_month_past': '您的信用卡已過期。',
  'invalid_expiry_year_past': '您的信用卡已過期。',
  'invalid_number': '您的卡號無效。',
  'payment': '付款',
  'payment_': '付款 ',
  'payment_date': '日期：',
  'payment_failed': '付款失敗',
  'payment_pending': '等待付款',
  'payment_succeeded': '付款成功',
  'pending_3ds': '等待3D-Secure驗證中',
  'receipt': '收據',
  'receipt_number': '收據編號：',
  'refunded': '已退款',
  'remove_card_confirm': '您是否確定要從電子銀包中移除此信用卡？',
  'save_card_data': '保存我的信用卡資料',
  'saved_card': '已儲存的信用卡',
  'select_payment_method': '選擇付款方法',
  'start_course': '開始課程',
  'succeeded': '成功',
  'view_receipt': '查看收據',
  'confirm_price': '確定價錢',
  'result': '結果',
  'view_invoice': '查看發票',
  'download_invoice': '下載發票',
  'cancel_subscription': '取消訂閱',
  'skip_auth': '跳過認證',
  'cancel_incompleted_subscription_confirm': '您是否確定要取消此未完成訂閱？',
  'cancel_incompleted_subscription_succeeded': '已成功取消此未完成訂閱',
  'new_plan': '新計劃',
  'remain_time_value': '剩餘的時間價值',
  'unused_time_value': '未用完的時間價值',
  'coupon_applied': '優惠碼已啟用',

  // shop
  'shop': '商店',

  // transaction
  'transaction': '交易紀錄',
  'action': '動作',
  'swap_subscription': '更換訂閱計劃',
  'renew_subscription': '續訂',
  'transfer': '轉移',
  'void': '空白',
  'pay': '付款',
  'my_transaction': '我的交易紀錄',
  'my_transaction_hint': '付款及交易紀錄',

  // company setting
  'setting': '設定',

  // plan
  'plan': '計劃',
  'plans': '計劃',
  'plan_management': '計劃管理',
  'create_plan': '新增計劃',
  'edit_plan': '編輯計劃',
  'delete_plan': '刪除計劃',
  'view_plan': '檢視計劃',
  'duplicate_plan': '複製計劃',
  'delete_plan_confirm': '你是否確定要刪除此計劃？',
  'activate_plan_confirm': '你是否確定要啟用此計劃？',
  'deactivate_plan_confirm': '你是否確定要停用此計劃？',
  'plan_info': '計劃資訊',
  'interval': '時限',
  'interval_unit': '時限單位',
  'interval_count': '時限數',
  'years': '年',
  'months': '月',
  'days': '日',
  'access_level': '訪問權限',

  // dollar
  'hkd': 'HK$',
  'HKD': 'HK$',
  'usd': 'US$',
  'USD': 'US$',

  // account
  'my_account': '我的帳戶',
  'personal_information': '個人資訊',
  'billing_information': '帳單資訊',
  'billing_information_hint': '定價及當前計劃',
  'no_billing': '沒有帳單',

  // wallet
  'my_wallet': '我的電子錢包',
  'wallet': '電子錢包',
  'add_card': '新增信用卡',
  'remove_card': '移除信用卡',
  'default_card': '默認卡',
  'save_default_card': '儲存為默認卡',
  'set_as_default': '設定為默認卡',
  'expiration_date': '到期日',
  'set_default_card_confirm': '你是否確定要把此卡設定為默認卡？',
  'set_default_card_hint': '默認卡將會在續訂時自動收費',
  'remove_card_failed': '不能移除此卡，如你未曾退訂，必須至少保留一張信用卡',
  'my_wallet_hint': '信用卡及付款方法',

  // course-rating
  'ratings&comments': '評分及評論',
  'course_review': '課程評論',
  'out_of': '滿分為',
  'edit_course_review': '更改課程評論',
  'click_star_to_rate': '按下星星來評分',
  'allow_user_edit': '允許用戶修改',
  'ratings': '評分',
  'comment': '評論',

  // learning-map
  'learning_map': '學習地圖',
  'learning_map_template': '學習地圖範本',
  'create_learning_map_template': '新增學習地圖範本',
  'edit_learning_map_template': '編輯學習地圖範本',
  'edit_template': '編輯範本',
  'more': '更多',

  'published_courses_count': '已發佈課程數量',
  'delete_learning_map_prompt': '你是否確定要刪除學習地圖',
  'delete_learning_map_desc': '有關此學習地圖的所有資料(包括已提交的資料)將會被刪除',
  'cannot_delete_learning_map': '不能刪除已發佈的學習地圖',
  'unpublish_learning_map_prompt': '你是否確定取消發佈此學習地圖？',
  'publish_learning_map_prompt': '你是否確定發佈此學習地圖？',

  'course_pool': '課程庫',
  'with_order': '依序排列',
  'finish_each_day': '需要每天完成',
  'finish_each_day_hint': '當用戶未按時完成時將發送提醒',
  'num_of_courses': '課程數量',
  'no_course_selected': '未選擇課程',
  'not_yet_select_course_hint': '有一些課程尚未選定',
  'confirm_edit_learning_map': '你是否確定要更改此學習地圖?',
  'edit_learning_map_hint': '有關此學習地圖的所有資料(包括已提交的資料)將會被重置',
  'less_course_hint': '你所輸入的課程數量少於現時已選擇的課程數量',
  'confirm_reselect_course': '你是否確定重新選擇全部課程?',
  'select_certificate': '請選擇證書',
  'learning_map_report': '學習地圖報告',
  'assigned_user': '已分配用戶',
  'course_selected': '已選擇課程',
  'remove_course': '移除課程',

  'assign_users': '分配用戶',
  'assign_users_prompt': '你是否確定分配用戶到此學習地圖？',
  'unassign_users_prompt': '你是否確定要刪除已分配用戶?',
  'learning_map_assign_users': '學習地圖分配用戶',
  'learning_map_assign_users_template': '學習地圖分配用戶Excel範本',
  'user_list': '用戶列表',
  'assigned_permissions': '已分配權限',

  'select_courses': '選擇課程',
  'loading': '加載中',

  // certificate
  'copy_certificate_template': '你是否確定要復制證書範本？',
  'delete_certificate_template': '你是否確定要刪除證書範本？',
  'create_certificate_template': '新增證書範本',
  'edit_certificate_template': '編輯證書範本',
  'orientation': '方向',
  'landscape': '橫向',
  'portrait': '縱向',
  'background_color': '背景顏色',
  'select_image': '選擇圖片',
  'subject_name': '學系名稱',
  'theme_name': '主題名稱',
  'certificate_no': '證書編號',
  'user_address': '用戶地址',
  'edit_certificate_template_clear': '你是否確定要清空證書?',
  'certificate_regenerate': '重新生成證書',
  'certificate_preview': '預覽證書',
  'certificate_clear': '清空證書',
  'add_content': '新增內容',
  'certificate_template': '證書範本',
  'course_name_en': '課程名稱 (英語)',
  'course_name_zh_hk': '課程名稱 (繁體中文)',
  'course_name_zh_cn': '課程名稱 (簡體中文)',
  'subject_name_en': '學系名稱 (英語)',
  'subject_name_zh_hk': '學系名稱 (繁體中文)',
  'subject_name_zh_cn': '學系名稱 (簡體中文)',
  'theme_name_en': '主題名稱 (英語)',
  'theme_name_zh_hk': '主題名稱 (繁體中文)',
  'theme_name_zh_cn': '主題名稱 (簡體中文)',
  'select_cert_temp':'選擇證書範本',
  'no_cert_temp_selected': '未選擇證書範本',

  // login
  'login_user_id_hint': '請輸入您的用戶編號',
  'login_password_hint': '請輸入您的密碼',
  'show_password': '顯示密碼',
  'hide_password': '隱藏密碼',

  'batch_actions': '批量操作',

  // notification
  'push_notification': '推送通知',
  'push_notification_management': '推送通知管理',
  'course_notification': '課程通知',
  'notice': '通告',
  'push_time': '推送時間',
  'send_failed': '發送失敗',
  'waiting_to_send': '等候發送',
  'pause': '暫停發送',

};
