// lang-en.ts
export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {

  // login
  'user_id': 'User ID',
  'user_name': 'User name',
  'email': 'Email',
  'password': 'Password',
  'company_id': 'Company ID',
  'login': 'Login',
  'language': 'Language',
  'register': 'Register',
  'forget_password': 'Forget Password',
  'disclaimer': 'Disclaimer',
  'disclaimer_message': "By logging in, you agree to the Disclaimer's terms.",
  'dont_have_account': 'Do not have an account?',
  'click_here_create': 'Click here to create company account',
  'internal_login': 'Internal Login',
  'company_login': 'Company Login',
  'use_another_account': 'Use Another Account',

  // register
  'company_full_name': 'Company Full Name',
  'company_short_name': 'Company Short Name',
  'required_to_fill_in': 'Required to fill in this field.',
  'confirm_password': 'Confirm Password',
  'invalid_email_address': 'Invalid email address',
  'password_not_match': 'Passwords don\'t match',

  // setting
  'change_language': 'Change Language',
  'change_language_alert': 'Are you sure to change the language: @{}?',
  'optional': 'optional',

  // timeout-box
  'timeout': 'Timeout',
  'timeout_prompt': 'Continue to use the platform',
  'time_left': 'Time left',
  'second': 'second(s)',
  'continue': 'Continue',
  'leave': 'Leave',

  //notification
  'notifications': 'Notifications',
  'cert_is_ready_hint': ': certification is ready',
  'download_certifications': 'Download certifications',
  'download_report': 'Download Report',

  // toast
  'ready_to_download': 'Ready to download',
  'download': 'Download',
  'download_input': 'Download @{}',
  'downloading': 'Downloading',
  'download_error': 'Download error',
  'download_completed': 'Download completed',
  'download_waiting_prompt': 'Please wait for the download to complete before continuing',
  'unable_to_download': 'Unable to download',
  'error_occurred': 'An error occurred',
  'details': 'Details',

  // page-not-found
  'page_not_found': 'Page Not Found',
  'page_not_exist': 'The page you are looking for does not exist',
  'previous_page_prompt': 'You can click the button below to go back to the previous page',
  'back': 'Back',
  'no_errors_found': 'No Errors Found',
  'close': 'Close',

  // page-no-permission
  'forbidden': 'Forbidden',
  'access_denied': 'Access denied',
  'no_permission_content': 'Sorry, you do not have permission to access this page',

  // layout
  'scroll_top': 'Top',
  'grid_view': 'Grid view',
  'list_view': 'List view',

  // header
  'logout': 'Logout',
  'welcome': 'Welcome',

  // dashboard
  'dashboard': 'Dashboard',
  'dashboard_statistics': 'Statistics',
  'dashboard_all_course_statistics': 'All Course Statistics',
  'dashboard_user_count': 'Number of users',
  'dashboard_course_count': 'Number of courses',
  'dashboard_login_count': 'Number of logins',
  'dashboard_devices': 'Devices',
  'dashboard_likes': 'Likes',
  'dashboard_recommendations': 'Recommendations',
  'dashboard_completions': 'Number of courses completed',
  'dashboard_enrollments': 'Number of courses enrolled',

  //department
  'department_id': "Department ID",
  'department_short_description': "Short Description",
  'department_long_description': "Long Description",
  "select_department": "Select Department(s)",
  "selected_department": "Selected Department(s) List",
  'self_department': "current",

  // course-management
  'course_management': 'Course Management',
  'online_courses': 'Online Courses',
  'offline_courses': 'Offline Courses',

  // user-management
  'user_management': 'User Management',
  'all_users': 'All Users',
  'admin_permission': 'Admin Permission',

  // subject
  'subject': 'Subject',
  'create_subject': 'Create Subject',
  'edit_subject': 'Edit Subject',
  'delete_subject': 'Delete Subject',

  // theme
  'theme': 'Theme',
  'create_theme': 'Create Theme',
  'edit_theme': 'Edit Theme',
  'delete_theme': 'Delete Theme',

  // actions
  'create': 'Create',
  'edit': 'Edit',
  'delete': 'Delete',
  'actions': 'Actions',
  'more_actions': 'More actions',
  'view': 'View',
  'search': 'Search',
  'searching': 'Searching',
  'save_and_next': 'Save & Next',
  'skip': 'Skip',
  'drag_and_reorder': 'Drag and reorder',
  'no_data_available': 'No Data available',
  'select': 'Select',
  'item(s)': 'item(s)',
  'selected': 'Selected',
  'checkbox_selected': 'Selected',
  'please_remove': 'Please remove',

  // subject-edit
  'name': 'Name',
  'lang_cn_short': '简',
  'lang_hk_short': '繁',
  'lang_en_short': 'ENG',
  'lang_cn_long': 'Simplified Chinese',
  'lang_hk_long': 'Traditional Chinese',
  'lang_en_long': 'English',
  'save': 'Save',
  'reset': 'Reset',
  'cancel': 'Cancel',
  'confirm_delete_prompt': 'Are you sure you want to delete this item?',
  'confirm_permanently_delete_prompt': 'Are you sure you want to delete this item permanently?',

  // course-edit
  'course': 'Course',
  'create_course': 'Create Course',
  'edit_course': 'Edit Course',
  'delete_course': 'Permanently Delete Course',
  'cover_image': 'Cover Image',
  'choose': 'Choose',

  //excel
  'browse': 'Browse',
  'select_file_with_appropriate_format': 'Please select a file with the appropriate format.',
  'download_excel_template': 'Download Excel Template',
  'excel_template': 'Excel Template',
  'preview': 'Preview',
  'import_excel': 'Import Excel',
  'import_by_excel': 'Import by Excel',
  'excel_format_incorrect': 'Excel format is incorrect',
  'excel_content_error': 'Excel content error',
  'excel_sheet_name_must_be': 'The excel sheet name must be',
  'excel_sheet_name_must_have': 'The excel sheet name must have',
  'no_excel_content': 'Cannot find Excel content',
  'no_relevant_information': 'No relevant information',
  'total': 'Total',
  'items': 'Items',
  'upload_failed': 'Upload Failed',
  'import_failed': 'Import Failed',
  'remarks': "Remarks",
  'delete_remarks': 'Please delete remarks and examples after finishing Excel',
  'fill_in_next_sheet': 'Please fill in the @{1} on the "@{0}" page',
  'create_template': 'Create "@{0}" Excel Template',

  //temp
  'entry_date': 'Entry Date',
  'account_expiry_date': 'Account Expiry Date',
  'user': 'User',
  'vocab': 'Vocab',
  'quiz': 'Quiz',
  'enrollment': 'Enrollment',

  // course
  'course_title_en': 'Event Name (English)',
  'course_title_zh_hk': 'Event Name (Traditional Chinese)',
  'course_title_zh_cn': 'Event Name (Simplified Chinese)',
  'event_code': 'Event Code',
  'course_confirm': 'Manager Confirmation (1-Yes, 0-No)',
  'public_quota': 'Seat Available',
  'enquiry_email': 'Enquiry Email',
  'course_format': 'Course completion report format (Training/ CPD Score)',
  'external_course_code': 'Course ID/ Course Code',
  'register_start_date': 'Enrollment Start Date (YYYY-MM-DD HH:mm)',
  'register_end_date': 'Enrollment Deadline (YYYY-MM-DD HH:mm)',
  'status': 'Status',

  // Lesson
  'lesson': 'Lesson',
  'lesson_content': 'Lesson Content',
  'order': 'Order',
  'lesson_title': 'Lesson Title',
  'lesson_start_date': 'Lesson Start Date (YYYY-MM-DD HH:mm)',
  'lesson_end_date': 'Lesson End Date (YYYY-MM-DD HH:mm)',
  'location': 'Location',
  'course_id': 'Course ID',
  'lesson_id': 'Lesson ID',
  'lesson_info': 'Lesson Info',
  'lesson_material': 'Lesson Material',
  'lesson_and_materials': 'Lesson & Materials',
  'edit_lesson': 'Edit Lesson',
  'delete_lesson': 'Permanently Delete Lesson',

  // Material
  'material': 'Material',
  'view_material': 'View Material',
  'add_material': 'Add Material',
  'edit_material': 'Edit Material',
  'delete_material': 'Delete Material',
  'add_attachment': 'Add File',
  'add_scorm': 'Add SCORM',
  'add_link': 'Add Link',
  'add_activity': 'Add Activity',
  'view_activity': 'View Activity',
  'edit_activity': 'Edit Activity',
  'attachment': 'File',
  'activity': 'Activity',
  'link': 'Link',
  'hyperlink': 'Link',
  'scorm': 'Scorm',
  'completion_criteria': 'Completion Criteria',
  'completed_when_opened': 'Completed when opened',
  'read_pdf_to_first': 'Read PDF to the first',
  'read_pdf_to_last': 'Read PDF to the last',
  'watch_video_to_first': 'Watch video to the first',
  'watch_video_to_last': 'Watch video to the last',
  'submit_activity': 'Submit Activity',
  'Page': 'Page',
  'page': 'page',
  'visible': 'Visible',
  'mark_visible': 'Mark as visible',
  'mark_invisible': 'Mark as invisible',
  'compulsory': 'Compulsory',
  'stream_pending': 'Waiting for conversion',
  'stream_generating': 'Converting',
  'stream_done': 'Done',
  'stream_failed': 'Failed',
  'store_attachment': 'Store file',
  'update_attachment_language': 'Update file language',
  'store_scorm': 'Store SCORM',
  'material_empty_file': 'Lesson materials include empty lesson files',
  'material_empty_link': 'Lesson materials include empty links',
  'material_link_no_http': 'The link must contain the word "http" or "https"',
  'others': 'Others',
  'download_file': 'Download file',
  'open_hyperlink': 'Open hyperlink',
  'Second': 'Second',
  'second_': 'second',
  'setting_completion_criteria': 'Setting completion criteria',
  'lesson_files': 'Lesson Files',
  'scorm_popup_block': 'We attempted to open the SCORM in a new window, but the popup is blocked. Please disable popup blockers for this site',
  'preview_scorm': 'Preview SCORM',
  'downloadable': 'Downloadable',
  'non_downloadable': 'Non-downloadable',
  'set_as_downloadable': 'Set as user downloadable',
  'set_as_non_downloadable': 'Set as user non-downloadable',

  // Activity
  'mcq': 'MCQ',
  'keyword': 'Keyword',
  'drawing': 'Drawing',
  'open_ended': 'Open-ended',
  'video': 'Video',
  'audio': 'Audio',
  'assignment': 'Assignment',
  'activity_name': 'Activity name',
  'activity_intro': 'Activity introduction',
  'background_image': 'Background image',
  'tag': 'Tag',
  'add_tag': 'Add Tag',
  'add_tag_hint': 'No more than 6 tags',
  'confirm_update_activity': 'Are you sure to update this activity? After you change the content, all previous data will be cleared.',

  // Scorm
  'version': 'Version',
  'accepted_scorm_version': 'Accept Scorm version 1.2 and 2004 only',

  // Discussion
  'discussion': 'Discussion',
  'topic': 'Topic',
  'topics': 'Topics',
  'start_discussion': 'Start a discussion',
  'create_topic': 'Create topic',
  'reply': 'Reply',
  'like': 'Like',
  'unlike': 'Unlike',
  'delete_topic': 'Delete discussion topic',
  'confirm_delete_topic': 'Are you sure to delete this discussion topic?',
  'delete_reply': 'Delete reply',
  'confirm_delete_reply': 'Are you sure to delete this reply?',
  'edit_topic': 'Edit discussion topic',
  'edit_reply': 'Edit reply',
  'choose_topic': 'Choose topic',
  'image_attachment': 'Image attachment',
  'content': 'Content',
  'pin_topic': 'Pin discussion topic',
  'unpin_topic': 'UnPin disucssion topic',
  'pin_reply': 'Pin reply',
  'unpin_reply': 'Unpin reply',

  // Quiz
  'create_course_quiz': 'Create Course Quiz',
  'create_lesson_quiz': 'Create Lesson Quiz',
  'edit_quiz': 'Edit Quiz',
  'delete_quiz': 'Delete Quiz',
  'quiz_title': 'Quiz Title',
  'passing_mark': 'Passing Mark',
  'need_time_limit': 'Need time limit',
  'time_limit': 'Time limit',
  'random_select_questions': 'Random select questions',
  'number_of_questions': 'Number of questions',
  'show': 'Show',
  'dont_display': 'Do not display',
  'display_correct_answer': 'Display correct answer',
  'display_answer_type': 'Display answer type',
  'display_all_answer': 'Display all answers',
  'display_wrong_only': 'Display wrong answers only',
  'display_mc_remarks': 'Display MC question remarks',
  'allow_redo': 'Allow redo',
  'allow': 'Allow',
  'not_allow': 'Not Allow',
  'fail_requires_retake': 'Fail requires retake',
  'number_of_fails': 'Number of fails',
  'total_number_of_question': 'Total number of question',
  'new_mc_question': 'New multiple choice question',
  'new_cloze_question': 'New Fill in the blank question',
  'mc_question': 'Multiple choice question',
  'cloze_question': 'Fill in the blank question',
  'max_choices': 'Maximum number of answers',
  'title': 'Title',
  'question': 'Question',
  'answer': 'Answer',
  'option': 'Option',
  'new_question': 'New Question',
  'new_option': 'New Option',
  'correct_answer': 'Correct Answer',
  'remark': 'Remark',
  'explanation': 'Explanation',
  'confirm_edit_quiz': 'Are you sure you want to edit this quiz?',
  'edit_quiz_hint': 'All information about the quiz (including submitted data) will be reset',
  'confirm_delete_quiz': 'Are you sure to permanaently delete this quiz?',
  'import_multiple_quizzes_error': 'Quiz cannot import more than one question bank',
  'quiz_no_questions': 'The quiz has no questions',
  'pass_mark_exceed_total': 'The number of qualified questions cannot exceed the number of questions',
  'no_random_question': 'No random question',
  'random_question_exceed_total': 'Number of random question cannot more than the number of question in the question bank.',
  'pass_mark_exceed_random': 'The number of qualified questions cannot exceed the number of random questions',
  'please_input_valid_value': 'Please input a valid value.',
  'max_choices_error': 'The maximum number of choices must be no less than 1 or the correct number of answers / The maximum number of choices can be no more than the number of options',
  'no_answers_error': 'Please choose the correct answer to multiple choice questions',
  'quiz_report': 'Quiz Report',
  'download_quiz_report': 'Download Quiz Report',
  'need_until_correct': 'Needs to be completely correct to complete',
  'time': 'Time',
  'pages': 'Page(s)',
  'show_video': 'Show video',
  'hide_video': 'Hide video',

  // Offline course
  'offlineCourse_courseEvent': 'Offline Course Event',

  // File Picker
  'select_file': 'Select File',
  'my_computer': 'My Computer',
  'internet': 'Internet',
  'drag_and_drop': 'Drag and Drop assets here',
  'or': 'Or',
  'upload_by_url_hint': 'Public URL of file to upload:',
  'upload_by_google_hint': 'Upload files from your Google Drive',
  'connect_to_google_drive': 'Connnet to Google Drive',
  'select_more': 'Select more',
  'reselect': 'Reselect',
  'upload': 'Upload',
  'clear': 'Clear',
  'type': 'Type',
  'size': 'Size',
  'file_not_found': 'File Not Found',
  'only_accept_file_type': 'Only accept file types:',
  'one_file_selected_only': 'Only one file can be selected',
  'load_image_failed': 'Load image failed',
  'cropping_image': 'Cropping image',
  'crop': 'Crop',
  'apply': 'Apply',
  'zoom_in': 'Zoom in',
  'zoom_out': 'Zoom out',
  'rotate': 'Rotate',
  'auto_padding': 'Auto padding',
  'remove_padding': 'Remove padding',
  'imageLimitHint': 'Can only upload images with no more than @{}',
  'fileLimitHint': 'Can only upload files with no more than @{}',
  'videoLimitHint': 'Can only upload video files with no more than @{}',

  // course-view
  'course_and_lessons': 'Course & Lessons',
  'course_settings': 'Course Settings',
  'delete_course_hint': 'Are you sure you want to delete this course permanently?',
  'permission_settings': 'Permission Settings',
  'compulsory_settings': 'Compulsory Settings',
  'enrollment_status': 'Enrollment Status',
  'course_quiz': 'Course Quiz',
  'lesson_quiz': 'Lesson Quiz',
  'evaluation': 'Evaluation',
  'course_certificate': 'Course Certificate',
  'create_lesson': 'Create Lesson',
  'published': 'Published',
  'unpublished': 'Unpublished',
  'confirm_unpublish_course': 'Are you sure to unpublish this course?',
  'confirm_publish_course': 'Are you sure to publish this course?',

  // Upload progress
  'upload_progress': "Upload Progress",
  'minimize_window': 'Minimize',
  'maximize_window': 'Maximize',
  'estimating_time': 'Estimating remain time ...',
  'completed': 'Completed',
  'upload_succeed': 'Upload Succeed',
  'pending': 'Pending',

  // Upload progress
  'download_progress': "Download Progress",
  'download_succeed': 'Download Succeed',
  'download_failed': 'Download Failed',

  // course-edit
  'description': 'Description',
  'twoFA': 'Two-factor authentication (2FA)',
  'yes': 'Yes',
  'no': 'No',
  'continual_identity_auth': 'Continual Identity Authentication',
  'biometric': 'Biometric',
  'google_auth': 'Google Auth',
  'have': 'Have',
  'has': 'Has',
  'have_yes': 'Yes',
  'have_no': 'No',
  'course_duration': 'Course Duration',
  'mins_short': 'Minutes',
  'minutes': 'Minutes',
  'seconds': 'Seconds',
  'enabled': 'Enabled',
  'disabled': 'Disabled',
  'multi_lang_missing_title_hint': 'Please fill in the name',
  'multi_lang_missing_description_hint': 'Please fill in the description',
  'multi_lang_missing_cover_hint': 'Please select a cover photo',
  'customize_image': 'Customize Photo',
  'new': 'New',
  'change_image': 'Change Image',
  'course_point': 'Course Point',
  'access_days_limit': 'Access Days Limit',

  // user-list
  'add_user': 'Add User',
  'department': 'Department',
  'job_rank': 'Job Rank',
  'view_and_edit': 'View & Edit',
  'activated': 'Activated',
  'deactivated': 'Deactivated',
  'item_per_page': 'Items per page:',
  'next_page': 'Next page',
  'previous_page': 'Previous page',
  'activation_title': 'User activation status change',
  'activation_content': 'Are you sure to change the status of the following users to',
  'restore': 'Restore',
  'confirm': 'Confirm',
  'icon': 'Icon',
  'locked_status': 'User locked status',
  'activate_user': 'Activate selected users',
  'deactivate_user': 'Deactivate selected users',
  'approve_user': 'Approve User',
  'approve_selected_user': 'Approve selected users',
  'reject_selected_user': 'Reject selected users',
  'cp_allocation': 'Course Points Allocation',
  'current_cp': 'Current course points',
  'cp_to_selected_users': 'Course points to each selected users',
  'required_cp': 'Required course points for this transaction',
  'remain_cp': 'Remain course after this transaction',
  'transfer_cp': 'Transfer course points',
  'cp_amount_min_error': 'Value cannot less than 1',
  'cp_amount_not_enough': 'Company do not have enough course points',
  'select_dept': 'Select department',
  'confirm_user_data': 'Confirm your input',

  //user-view
  'external_id': 'User ID',
  'basic_info': 'Basic Information',
  'course_info': 'Course Information',
  'permission_info': 'Permission Information',
  'user_title': 'User title',
  'change_password_hint': 'Change if needed',
  'user_report': 'User report',
  'create_user': 'Create User',
  'profile': 'Profile',
  'compulsory_courses': 'Compulsory courses',
  'non-compulsory': 'Elective courses',
  'recommended': 'Recommended courses',
  'pass': 'Pass',
  'achievements': 'Achievements',
  'user_course_data': 'User course data',
  'completed_courses': 'Completed courses',
  'in_progress_courses': 'In progress courses',
  'valid_password_alert_msg': 'Please enter a valid password',

  //user-view-course-info
  'subject_title': 'Subject',
  'theme_title': 'Theme',
  'course_title': 'Course',
  'pivot_start_date': 'Start time',
  'completion_status': 'Completion status',
  'pivot_end_date': 'Completion time',
  'has_quiz': 'Quiz',
  'not_yet_assessed': 'Not yet assessed',
  'no_assessment': 'No assessment',
  'certificate': 'Certificate',

  //admin
  'add_admin': 'Add Admin',
  'user_employed': 'Employed',
  'admin_user_list': 'Admin Management',
  'create_user_admin': 'Add New Admin',
  'update_user_admin': 'Update Admin',
  'role_title': 'Role Title',
  'role_titles': 'Role Title(s)',
  'permission': 'Permission(s)',
  'viewable_department_titles': 'Managable Department(s)',
  'role_list': 'Role Management',
  'create_role': 'Add New Role',
  'update_role': 'Update Role',
  'new_role': 'New Role',
  'delete_role': 'Permanently Delete Role',
  'delete_role_hint': 'Are you sure you want to delete this role permanently? After you deleted the role, users who are assigned to this role will no longer have the permission.',
  'all_permissions': 'All Permissions',
  'role_name_incorrect': 'Please use another name.',
  'role_name_letter_incorrect': 'Please use only letters(a-z/A-Z), numbers or spaces.',
  'admin_step1': 'Select User(s)',
  'admin_step2': 'Add Role(s)',
  'admin_step3': 'Add Manageable Department(s)',
  'admin_update_step2': 'Update Role(s)',
  'admin_update_step3': 'Update Manageable Department(s)',
  'select_roles': 'Select Role(s)',
  'admin_other_roles': 'Other Role(s)',
  'user_current_department': "user's department",

  //abilities name
  'User Management': 'User Management',
  'Manage Reports': 'Manage Reports',
  'Company Management': 'Company Management',
  'Unit Management': 'Unit Management',
  'Login CMS': 'Login CMS',
  'Login Teacher website': 'Login Teacher website',
  'Manage users': 'Manage users',
  'Admin permission': 'Admin permission',
  'Department Management': 'Department Management',
  'overall_course_report': 'Overall Course Report',
  'course_participation_report': 'Course Participation Report',
  'course_completion_report': 'Ccourse Completion Report',
  'overall_user_report': 'Overall User Report',
  'user_individual_report': 'User Individual Report',
  'overall_user_login_report': 'Overall User Login Report',
  'Push Notification': 'Push Notification',
  'Banner': 'Banner',
  'Highlight Management': 'Highlight Management',
  'Highlight Topic Management': 'Highlight Topic Management',
  'Mock Exam': 'Mock Exam',
  'Discussion': 'Discussion',
  'Learning Map': 'Learning Map',
  'Course Certificate': 'Course Certificate',
  'Vocabulary': 'Vocabulary',
  'Offline Courses': 'Offline Courses',
  'Material Library': 'Material Library',
  'System Management': 'System Management',
  'Manage Units': 'Manage Units',
  'Manage Plan': 'Manage Plans',
  'Manage Products': 'Manage Products',
  'Trainer Management': 'Trainer Management',

  // image-viewer
  'no_image_found': 'No Image Found',

  // Qti
  'qti_format': 'QTI format',
  'about_qti': 'About QTI',
  'import_qti': 'Import QTI',
  'import_by_qti_format': 'Import by QTI format',
  'download_qti': 'Download quiz of QTI format',
  'accept_qti_version': 'Accept QTI version 2.0, 2.1, 2.2 only',
  'qtiQuiz': 'QTI Quiz',
  'qti_quiz': 'QTI Quiz',
  'add_qti_quiz': 'Add QTI quiz',
  'submit_quiz': 'Submit quiz',
  'test_id': 'Test ID',
  'store_qti_quiz': 'Score QTI Quiz',
  'download_qti_quiz': 'Download QTI quiz file',
  'preview_qti_quiz': 'Preview QTI quiz',
  'qti_intro': 'QTI introduction',
  'supported_version': 'Supported versions',
  'supported_question_type': 'Supported question types',
  'qti_quiz_tutorial': 'Make QTI quiz tutorial',
  'qti_intro_paragraph_1': 'The IMS Question and Test Interoperability specification (QTI) defines a standard format for the representation of assessment content and results, supporting the exchange of this material between authoring and delivery systems, repositories and other learning management systems. It allows assessment materials to be authored and delivered on multiple systems interchangeably. It is, therefore, designed to facilitate interoperability between systems.',
  'qti_intro_paragraph_2': 'The specification consists of a data model that defines the structure of questions, assessments and results from questions and assessments together with an XML data binding that essentially defines a language for interchanging questions and other assessment material. The XML binding is widely used for exchanging questions between different authoring tools and by publishers. The assessment and results parts of the specification are less widely used.',
  'support': 'Support',
  'suggest': 'Suggest',
  'question_type': 'Question type',
  'mobile': 'Mobile',
  'desktop': 'Desktop',
  'qti_more_detail': 'For more information, please refer to the following links',
  'qti_structure_paragraph_1': 'To make a QTI quiz, you need to upload a .zip file package, which contains the test, part, section, item in .xml format, and various materials required for the items. The initial file must be named index.xml and must contain the assessmentTest tag, otherwise the system cannot read it.',

  // multi-lang-basic
  'primary_language': 'Primary Language',
  'update': 'Update',

  // search-box
  'search_add': 'Add Item',

  // course-setting
  'quiz_will_be_deleted': 'Quiz will be deleted',
  'evaluation_will_be_deleted': 'Evaluation will be deleted',
  'confirm_multi_delete': 'Are you sure you want to delete: @{}?',
  'delete_hint': 'All data (include submitted data) will be deleted',

  // evaluation-edit
  'confirm_delete_evaluation': 'Are you sure you want to delete the evaluation?',
  'delete_evaluation': 'Delete Evaluation',
  'confirm_edit_evaluation': 'Are you sure you want to change the content of the evaluation?',
  'edit_evaluation_hint': 'All information about this evaluation (including submitted information) will be reset',
  'evaluation_title': 'Evaluation Title',
  'import_template': 'Import Default Questions',
  'section_title': 'Section Title',
  'delete_section': 'Delete Section',
  'new_section': 'New Section',
  'score_question': 'Score Question',
  'lowest_display_text': 'Lowest Display Text',
  'highest_display_text': 'Highest Display Text',
  'score_question_range': 'Range',
  'open_ended_question': 'Open-ended Question',
  'new_score_question': 'New Score Question',
  'new_open_ended_question': 'New Open-ended Question',
  'evaluation_no_sections': 'Evaluation has no sections',
  'question_required': 'At least one question is required',
  'options_required': 'At least two options is required',
  'edit_evaluation_template': 'Edit Default Question',
  'create_evaluation_template': 'Create Default Question',
  'save_template': 'Save Default Question',
  'cancel_template': 'Cancel Default Question',
  'delete_template': 'Delete Default Question',
  'confirm_edit_evaluation_template': 'Are you sure you want to change the content of the default question?',
  'confirm_create_evaluation_template': 'Are you sure you want to create the content of the default question?',
  'confirm_delete_template': 'Are you sure you want to delete the default question?',
  'confirm_cancel_edit_evaluation_template': 'Are you sure you want to cancel change the content of the default question?',
  'confirm_cancel_create_evaluation_template': 'Are you sure you want to cancel create the content of the default question?',
  'confirm_cancel_edit_evaluation': 'Are you sure you want to cancel change the content of the evaluation?',
  'save_succeed': 'Save Succeed',

  // course-enrollment
  'course_enrolled_users': 'Enrolled users',
  'course_new_enrollment': 'New Enrollment',
  'course_enroll_users': 'Course Enrollment',
  'start_time': 'Start Time',
  'completion_time': 'Completion Time',
  'not_yet_completed': 'Not yet completed',
  'ok': 'OK',
  'reorder': 'Reorder',
  'move_up': 'Move up',
  'move_down': 'Move down',
  'course_name': 'Course Name',
  'search_result': 'Search Results',
  'clear_search_result': 'Clear Search Results',
  'total_num_result_text': 'Total @{} results',
  'delete_enrolled_user_prompt': 'Are you sure you want to delete enrolled users?',
  'view_user': 'View User',
  'expiry_date': 'Expiry Date',

  // mock-exam
  'mockexam': 'Mock Exam',
  'mockexam_management': 'Mock Exam Management',
  'create_mockexam': 'Create Mock Exam',
  'number_of_completions': 'Number of Completions',
  'qualified_number': 'Qualified Number',
  'average_score': 'Average Score',
  'edit_mockexam_confirm': 'Are you sure you want to edit this mock exam?',
  'delete_mockexam_confirm': 'Are you sure you want to delete the mock exam',
  'delete_mockexam_hint': 'All information about this mock exam (including submitted material) will be deleted.',
  'publish_mockexam_confirm': 'Are you sure to publish this mock exam?',
  'unpublish_mockexam_confirm': 'Are you sure to unpublish this mock exam?',
  'cannot_edit_published_mockexam': 'Cannot edit a published mock exam',
  'cannot_delete_published_mockexam': 'Cannot delete a published mock exam',
  'publish': 'Publish',
  'section': 'Section',
  'create_section': 'Create new section',
  'required': 'Required',

  // question-bank
  'question_bank': 'Question Bank',
  'create_question_bank': 'Create question bank',
  'edit_question_bank_confirm': 'Are you sure you want to edit this question bank?',
  'delete_question_bank_confirm': 'Are you sure you want to delete the question bank',
  'delete_question_bank_hint': 'All information about this question bank (including those submitted in the mock exam) will be deleted.',
  'import_multiple_question_bank_error': 'Cannot import more than one question bank',

  // download-excel-template-btn
  'excel_remarks_sample_sheet': 'This is a sample page, please fill in the data on the @{} page',

  // quiz-basic
  'import_quiz_template': 'Import Quiz Excel Template',
  'excel_remarks_one_quiz': 'Only allow import one quiz in this sheet, please fill in the same title',
  'excel_remarks_mc_question': 'If this is a multiple choice question, please fill in the option number in Answer',
  'excel_remarks_fill_question': 'If this is a fill in the blank question, please fill in the correct answer in the Answer field and no need to fill in the MC Option columns',

  // question-bank
  'import_question_bank_template': 'Import Question Bank Excel Template',
  'excel_remarks_one_question_bank': 'Only allow import one question bank in this sheet, please fill in the same title and description',
  'excel_remarks_mc_question_option': 'please fill in the option number in Answer',
  'excel_remarks_same_question_bank': 'If the question is in the same question bank, please fill in the same title and description',

  // banner
  'home_page': 'Home Page',
  'banner': 'Banner',
  'banners': 'Banners',
  'login_banners': 'Login Banners',
  'banner_management': 'Banner Management',
  'login_banner_management': 'Login Banner Management',
  'create_banner': 'Create Banner',
  'create_login_banner': 'Create Login Banner',
  'edit_banner': 'Edit Banner',
  'delete_banner': 'Delete Banner',
  'delete_banner_confirm': 'Are you sure you want to delete this banner?',
  'website_url': 'Website URL',
  'banner_status': 'Status',
  'no_banner': 'No banner',
  'reorder_confirm': 'Save the order?',

  // highlight
  'highlight_management': 'Highlight Management',
  'highlight': 'Highlight',
  'create_highlight': 'Create Highlight',
  'edit_highlight': 'Edit Highlight',
  'delete_highlight': 'Delete Highlight',
  'create_highlight_topic': 'Create Highlight Topic',
  'edit_highlight_topic': 'Edit Highlight Topic',
  'delete_highlight_topic': 'Delete Highlight Topic',

  // course-view
  'leave_page_hint': 'Are you sure you want to leave this page?',
  'leave_page_desc': 'The system will not save your changes',

  //unit
  'unit_management': 'Company Management',
  'create_unit': 'Add Company',
  'update_unit': 'Update Company',
  'unit_id': 'Company ID',
  'unit_list': 'Company List',
  'unit': 'Company',
  'new_unit': 'New Company',
  'unit_info': 'Company Information',
  'unit_user': 'Company Member',
  'unit_admin': 'Company Admin',
  'add_unit_user': 'Add Company Member',
  'add_unit_admin': 'Add Company Admin',
  'short_description': "Short Description",
  'long_description': "Long Description",
  'unit_missing_short_description': 'Please fill in the short description',
  'unit_missing_long_description': 'Please fill in the long description',
  'unit_delete_hint': 'Are you sure you want to delete the company?',
  'unit_delete_admin_hint': 'Are you sure you want to delete the Company Admin(s)?',
  'approved': 'Approved',
  'unit_approve_hint': 'Are you sure you want to approve the unit?',
  'unit_unapprove_hint': 'Are you sure you want to unapprove the unit?',
  'default_unit_not_editable': 'Cannot edit default unit',

  //department
  'department_management': 'Department Management',
  'department_name': 'Department Name',
  'department_parent_id': 'Parent Department ID',
  'department_parent_long_description': 'Parent Department Name',
  'create_department': 'Create Department',
  'update_department': 'Update Department',
  'new_department': 'New Department',
  'department_delete_hint': 'Are you sure you want to delete the department?',
  'department_missing_external_id': 'Please fill in the department id',
  'parent_department': 'Parent Department',
  'department_manager': 'Department Manager',
  'add_department_manager': 'Select A Department Manager',
  'add_department_parent': 'Select A Parent Department',
  'duplicated_department_external_id_hints': 'Department ID is already in use, please enter a valid department id.',
  'department_cannot_delete_hint': 'Unable to delete the department',
  'department_has_manager_hint': 'manager',
  'department_has_children_hint': 'children department(s)',

  //widget-table
  'filter_columns': 'Filter Columns',

  // course-enrollment-dialog
  'select_user': 'Select User(s)',
  'edit_list': 'Edit List',
  'next_step': 'Next',
  'previous_step': 'Back',

  // course-compulsory
  'confirm_delete_selected_prompt': 'Are you sure you want to delete the selected items?',
  'compulsory_due_date': 'Complete Date',
  'compulsory_users': 'Compulsory Users',
  'add_compulsory_users': 'Add Compulsory Users',
  'compulsory_departments': 'Compulsory Departments',
  'add_compulsory_departments': 'Add Compulsory Departments',
  'import_user_template': 'Import User Excel Template',

  'course_reminder': 'Course Reminder',
  'send_course_reminder': 'Send Reminder',
  'not_completed_users': 'All users who have not completed the course',
  'course_compulsory_reminder': 'The system will automatically send a reminder before @{} days of the complete date',
  'sending': 'Sending',
  'sent': 'Sent',

  // user-abilities-setting
  'user_permission': 'User Permission',
  'admin_permission_settings': 'Admin Permission Settings',

  // course-permission
  'default_permissions': 'Default Permissions',
  'has_permission_list': 'Has Permission List',
  'no_permission_list': 'No Permission List',
  'has_permission': 'Has Permission',
  'no_permission': 'No Permission',
  'add_permissions': 'Add Permissions',
  'cancel_permission': 'Cancel Permission',
  'change_default_permissions_propmt': 'Are you sure you want to change the default permissions?',
  'cancel_permissions_propmt': 'Are you sure you want to cancel the permission of the selected item?',
  'cancel_existing_permissions': 'Cancel Existing Permissions',
  'existing_permissions': 'Existing Permissions',
  'add_input': 'Add @{}',
  'create_input': 'Create @{}',
  'edit_input': 'Edit @{}',
  'change_input': 'Change @{}',
  'add_items': 'Add Items',
  'select_item': 'Select Item(s)',
  'select_job_rank': 'Select Job Rank',
  'join_date': 'Join Date',
  'selected_date': 'Selected Date',
  'from': 'From',
  'to': 'To',

  //trainer
  'trainer': 'Trainer',
  'trainers': 'Trainers',
  'trainer_managemnet': 'Trainer Management',
  'create_trainer': 'Create Trainer',
  'edit_trainer': 'Edit Trainer',
  'remove_trainer': 'Remove Trainer Role',
  'trainer_description': 'Trainer Description',
  'remove_trainer_role_confirm': 'Are you sure to remove the trainer role to user?',
  'avatar': 'Avatar',
  'add_trainer_description': 'Add Trainer Description',

  // product
  'product': 'Product',
  'products': 'Products',
  'product_management': 'Product Management',
  'create_product': 'Create Product',
  'edit_product': 'Edit Product',
  'delete_product': 'Delete Product',
  'view_product': 'View Product',
  'duplicate_product': 'Duplicate Product',
  'seat': 'Seats',
  'storage': 'Storage',
  'free': 'Free',
  'user_shop': 'User Shop',
  'company_shop': 'Company Shop',
  'price': 'Price',
  'currency': 'Currency',
  'delete_product_confirm': 'Are you sure you want to delete the product?',
  'activate_product_confirm': 'Are you sure you want to activate the product?',
  'deactivate_product_confirm': 'Are you sure you want to deactivate the product?',
  'product_info': 'Product Information',
  'web_platform': 'Web platform',
  'ios_platform': 'iOS platform',
  'android_platform': 'Google Pay platform',
  'purchase': 'Purchase',
  'purchase_product': 'Purchase Product',


  // income report
  'income_report': 'Income Report',
  'stripe_transaction': 'Stripe Transaction',
  'ios_transaction': 'iOS Transaction',
  'android_transaction': 'Android Transaction',
  'count': 'Count',
  'amount': 'Amount',
  'stripe_processing_fee': 'Stripe Processing Fee',
  'stripe_processing_fee_hint': '(basic: 3.4% + HK$2.35)',
  'ios_fee': 'iOS Fee',
  'android_fee': 'Android Fee',
  'final_net': 'Final Net',
  'each': 'each',
  'cp_transaction': 'Course Point Transaction',
  'cp_fee': 'Course Point Fee',

  // transaction
  'income_records': 'Income Records',
  'date': 'Date',
  'customer': 'Customer',
  'fee': 'Fee',
  'net': 'Net',
  'platform': 'Platform',
  'coupon': 'Coupon',
  'refund': 'Refund',
  'refund_type': 'Refund type',
  'no_refund': 'No refund',
  'refunded_by_hkd': 'Refunded by HKD',
  'refund_by_cp': 'Refund by course points',
  'refund_amount': 'Refund amount',
  'withdraw_resources': 'Withdraw resources',
  'ban_access_to_course': 'Ban access to course',

  // system
  'system': 'System',
  'system_management': 'System Management',

  // user-abilities
  'all_course_permissions': 'All Course Permissions',
  'create_quiz': 'Create Quiz',
  'view_quiz_report': 'View Quiz Report',
  'create_evaluation': 'Create Evaluation',
  'view_evaluation_report': 'View Evaluation Report',
  'view_discussion': 'View Discussion',
  'set_permissions': 'Set Permissions',
  'remove_course_abilities_disabled_hint': 'Please remove the permission at the @{} level',
  'remove_course_abilities': 'Remove Permissions',
  'no_selected_permission_hint': 'Please select at least one permission',
  'change_all_ability_hint': 'Please change the permissions on the admin permission page',
  'view_only': 'View Only',
  'editor': 'Editor',
  'save_course_abilities_prompt': 'Are you sure you want to save the admin permission settings?',

  // evaluation
  'evaluation_report': 'Evaluation Report',
  'download_evaluation_report': 'Download Evaluation Report',
  'incorrect_content': 'Incorrect Content',
  'settings': 'Settings',

  // reports
  'reports': 'Reports',
  'course_reports': 'Course Reports',
  'user_reports': 'User Reports',
  'system_data': 'System Data',
  'num_enrollment': 'Number of Enrollment',
  'num_finished_users': 'Number of Finished Users',
  'course_hours': 'Course Hours',
  'all_courses': 'All Courses',
  'created_date': 'Created Date',
  'updated_date': 'Updated Date',
  'num_lessons': 'Number of Lessons',
  'assessment_method': 'Assessment Method',
  'filter_course_report': 'Filter Course Report',
  'all_courses_report': 'All Courses Report',
  'all_users_report': 'All Users Report',
  'department_report': 'Department Report',
  'login_report': 'User Login Report',
  'recommendation_report': 'Recommendation Report',
  'course_report': 'Course Report',
  'report_is_ready_hint': ' is ready for download.',

  'hr_status': 'HR Status',
  'recommended_count': 'Number of Courses Recommended',
  'enrolled_courses_count': 'Number of Courses Enrolled',
  'completed_courses_count': 'Number of Courses Completed',
  'passed_courses_count': 'Number of Courses Passed',
  'likes_count': 'Number of Courses Liked',
  'user_expiry': 'Resign Date',
  'filter_user_report': 'Filter User Report',
  'year': 'Year',
  'month': 'Month',
  'day': 'Day',

  // months
  'month_1': 'January',
  'month_2': 'February',
  'month_3': 'March',
  'month_4': 'April',
  'month_5': 'May',
  'month_6': 'June',
  'month_7': 'July',
  'month_8': 'August',
  'month_9': 'September',
  'month_10': 'October',
  'month_11': 'November',
  'month_12': 'December',

  'select_all': 'Select All',
  'unselect_all': 'Unselect All',
  'select_hint': 'Please Select',
  'select_all_search_result': 'Select All Search Results',
  'unselect_all_search_result': 'Unselect All Search Results',
  'login_report_disabled_hint': 'Please Select Year and Month',

  // Zoom Meeting
  'add_zoom_meeting': 'Add Zoom Meeting',
  'edit_zoom_meeting': 'Edit Zoom Meeting',
  'zoom_input_meeting': 'Input an existing Zoom meeting',
  'zoom_create_meeting': 'Create a new Zoom Meeting',
  'zoom_meeting_title': 'Meeting Title',
  'zoom_meeting_description': 'Meeting Description',
  'zoom_meeting_id': 'Meeting ID',
  'zoom_meeting_start_date': 'Meeting Start Date and Time',
  'zoom_duration': 'Meeting duration',
  'zoom_password_hint': 'Max 10 characters',
  'view_zoom_meeting': 'View Zoom Meeting',
  'open_zoom_meeting': 'Open Zoom Meeting Join Link',
  'zoom_not_enabled': 'Connecting to the Zoom account is not supported.',
  'zoom_oauth_message_title': 'Zoom Account Authorization is Required!',
  'zoom_oauth_message_content': 'Please complete the procedure in the pop-up link. Click confirm once you had finished the authorization.',
  'Zoom Meeting': 'Zoom Meeting',
  'zoom_meeting': 'Zoom Meeting',
  'zoom_install_title': 'Connect To Your Zoom Account',
  'zoom_install_first': 'If you wish to connect your Zoom account to iTrain. Please click',
  'here': 'here',
  'zoom_install_second': ' to complete the authorization.',
  'zoom_uninstall_first': 'You may uninstall it anytime at ',
  'zoom_uninstall_second': '',
  'zoom_not_allowed_to_update': 'This Zoom Meeting can only be edited by its creator(@{}).',

  'no_subject': 'No Subject',
  'no_theme': 'No Theme',
  'no_course': 'No Course',
  'no_lesson': 'No Lesson',

  // course-statistics
  'course_statistics': 'Course Statistics',
  'course_creation_date': 'Course Creation Date',
  'last_update_time': 'Last Update Time',
  'start_date': 'Start Date',
  'end_date': 'End Date',
  'all': 'All',
  'this_month': 'This Month',
  'this_quarter': 'This Quarter',
  'this_year': 'This Year',

  'num_completion': 'Number of  Completion',
  'num_incompletion': 'Number of  Incompletion',
  'overall_num_enrollment': 'Overall Number of Enrollment',
  'overall_num_completion': 'Overall Number of  Completion',

  // verify email
  'verification_code': 'Verification code',
  'verify': 'Verify',
  'verify_email': 'Verify your email',
  'verify_email_hint': 'We have just send you a verification code via your email.',
  'verify_failed': 'Verification code incorrect.',
  'verify_succeed': 'Verify succeed.',
  'dont_receive_code': 'Don\'t receive the code?',
  'has_been_resent': 'Has been resent, please check',
  'next_resend': 'Next resend chance:',
  'resend': 'Resend',

  // company
  'company_management': 'Company Management',
  'company_info': 'Company Information',
  'usage': 'Usage',

  // subscription
  'subscription': 'Subscription',
  'subscription_info': 'Subscription Information',
  'current_plan': 'Current Plan',
  'next_plan': 'Next Plan',
  'plan_title': 'Plan Title',
  'plan_description': 'Plan Description',
  'period': 'Period',
  'paid_by': 'Paid By',
  'subscribe': 'Subscribe',
  'active': 'Active',
  'incomplete': 'Incomplete payment',
  'incomplete_expired': 'Incomplete payment and expired',
  'trialing': 'Trialing',
  'past_due': 'Past due',
  'canceled': 'Canceled',
  'unpaid': 'Unpaid',
  'unsubscribe': 'Unsubscribe',
  'resume_subscription': 'Resume subscription',
  'change_plan': 'Change plan',
  'unsubscribe_confirm': 'Are you sure to unsubscribe current plan?',
  'unsubscribe_succeeded': 'Unsubscribe succeeded',
  'resume_subscription_confirm': 'Are you sure to resume subscription?',
  'resume_subscription_hint': 'This action will cancel your scheduled subscription',
  'resume_subscription_succeeded': 'Resume subscription succeeded',
  'unsubscribed': 'Unsubscribed',
  'service_end_at': 'Service end at',
  'upgrade_now': 'Upgrade now',
  'change_plan_period_end': 'Change plan at the period end',
  'scheduling_next_plan': 'Scheduling next plan',
  'next_plan_scheduled': 'Next plan scheduled',
  'subscription_change_and_charge_at': 'Your subscription will automatically charge and change to this plan at',
  'cancel_scheduled_subscription': 'Cancel schedule subscription',
  'cancel_scheduled_subscription_confirm': 'Are you sure to cancel scheduled subscription?',
  'cancel_scheduled_subscription_succeeded': 'Cancel schedule subscription succeeded',

  // payment
  'add_payment_method': 'Add payment method',
  'cancel_payment': 'Cancel payment',
  'card': 'Card',
  'card_data': 'Card data',
  'card_number': 'Card number',
  'charge_id': 'Charge ID:',
  'confirm_3ds': 'Confirm 3D-Secure',
  'confirm_payment': 'Confirm payment',
  'coupon_code': 'Coupon code',
  'coupon_discount_less_hint': 'The coupon code discount is less than 1 course point. This coupon code is invalid.',
  'error_code': 'Error code',
  'failed': 'Failed',
  'incomplete_cvc': 'Incomplete CVC.',
  'incomplete_expiry': 'Incomplete expiry date',
  'incomplete_number': 'Incomplete card number',
  'incomplete_payment': 'Incomplete payment',
  'invalid_coupon': 'Invalid coupon code',
  'invalid_expiry_month_past': 'Your card is expired.',
  'invalid_expiry_year_past': 'Your card is expired.',
  'invalid_number': 'Your card number is invalid.',
  'payment': 'Payment',
  'payment_': 'Payment ',
  'payment_date': 'Date:',
  'payment_failed': 'Payment failed',
  'payment_pending': 'Payment pending',
  'payment_succeeded': 'Payment succeeded',
  'pending_3ds': 'Pending for 3D-Secure authentication',
  'receipt': 'Receipt',
  'receipt_number': 'Receipt no.:',
  'refunded': 'Refunded',
  'remove_card_confirm': 'Are you sure you want to remove the card from e-wallet?',
  'save_card_data': 'Save my card data',
  'saved_card': 'Saved card',
  'select_payment_method': 'Select payment method',
  'start_course': 'Start course',
  'succeeded': 'Succeeded',
  'view_receipt': 'View receipt',
  'confirm_price': 'Confirm Price',
  'result': 'Result',
  'view_invoice': 'View Invoice',
  'download_invoice': 'Download Invoice',
  'cancel_subscription': 'Cancel Subscription',
  'skip_auth': 'Skip Authentication',
  'cancel_incompleted_subscription_confirm': 'Are you sure to cancel this incomplete subscription?',
  'cancel_incompleted_subscription_succeeded': 'Cancel incomplete subscription successfully.',
  'new_plan': 'New plan',
  'remain_time_value': 'Remaining subscription time cost',
  'unused_time_value': 'Unused subscription time cost',
  'coupon_applied': 'Coupon Applied',

  // shop
  'shop': 'Shop',

  // transaction
  'transaction': 'Transaction',
  'action': 'Action',
  'swap_subscription': 'Swap subscription',
  'renew_subscription': 'Renew subscription',
  'transfer': 'Transfer',
  'void': 'Void',
  'pay': 'Pay',
  'my_transaction': 'My Transaction Records',
  'my_transaction_hint': 'Payment & Transaction Records',


  // company setting
  'setting': 'Setting',

  // plan
  'plan': 'Plan',
  'plans': 'Plans',
  'plan_management': 'Plan Management',
  'create_plan': 'Create Plan',
  'edit_plan': 'Edit Plan',
  'delete_plan': 'Delete Plan',
  'view_plan': 'View Plan',
  'duplicate_plan': 'Duplicate Plan',
  'delete_plan_confirm': 'Are you sure you want to delete the plan?',
  'activate_plan_confirm': 'Are you sure you want to activate the plan?',
  'deactivate_plan_confirm': 'Are you sure you want to deactivate the plan?',
  'plan_info': 'Plan Information',
  'interval': 'Interval',
  'interval_unit': 'interval Unit',
  'interval_count': 'Interval Count',
  'years': 'Year(s)',
  'months': 'Month(s)',
  'days': 'Day(s)',
  'access_level': 'Access Level',

  // dollar
  'hkd': 'HK$',
  'HKD': 'HK$',
  'usd': 'US$',
  'USD': 'US$',

  // account
  'my_account': 'My Account',
  'personal_information': 'Personal Information',
  'billing_information': 'Billing Information',
  'billing_information_hint': 'Pricing & Current Plan',
  'no_billing': 'No billing',

  // wallet
  'my_wallet': 'My E-Wallet',
  'wallet': 'E-Wallet',
  'add_card': 'Add Card',
  'remove_card': 'Remove card',
  'default_card': 'Default card',
  'save_default_card': 'Save as default card',
  'set_as_default': 'Set as default card',
  'expiration_date': 'Expiration date',
  'set_default_card_confirm': 'Are you sure you want to set this card as default?',
  'set_default_card_hint': 'Default card will be used in automatically charged when renewing subscription.',
  'remove_card_failed': 'Cannot remove this card, you must store at least one card if you not yet unsubscribed',
  'my_wallet_hint': 'Credit Cards & Payment Methods',

  // course-rating
  'ratings&comments': 'Ratings & Comments',
  'course_review': 'Course Review',
  'out_of': 'out of',
  'edit_course_review': 'Edit course review',
  'click_star_to_rate': 'Click star to rate',
  'allow_user_edit': 'Allow user edit',
  'ratings': 'Ratings',
  'comment': 'Commnet',

  // learning-map
  'learning_map': 'Learning Map',
  'learning_map_template': 'Learning Map Template',
  'create_learning_map_template': 'Create Learning Map Template',
  'edit_learning_map_template': 'Edit Learning Map Template',
  'edit_template': 'Edit Template',
  'more': 'More',

  'published_courses_count': 'Number of Published Courses',
  'delete_learning_map_prompt': 'Are you sure you want to delete the learning map',
  'delete_learning_map_desc': 'All information about this learning map (including submitted materials) will be deleted',
  'cannot_delete_learning_map': 'Cannot delete a published learning map',
  'unpublish_learning_map_prompt': 'Are you sure to unpublish this learning map?',
  'publish_learning_map_prompt': 'Are you sure to publish this learning map?',

  'course_pool': 'Course Pool',
  'with_order': 'With Order',
  'finish_each_day': 'Need to finish on each day',
  'finish_each_day_hint': 'A reminder will be sent when the user does not finish on time',
  'num_of_courses': 'Number of Courses',
  'no_course_selected': 'No Course Selected',
  'not_yet_select_course_hint': 'There are some of the course not yet selected',
  'confirm_edit_learning_map': 'Are you sure you want to edit this learning map?',
  'edit_learning_map_hint': 'All information about this learning map (including submitted materials) will be reset',
  'less_course_hint': 'The number of courses you have entered is less than the number of courses currently selected',
  'confirm_reselect_course': 'Are you sure to reselect all courses?',
  'select_certificate': 'Please select a certificate',
  'learning_map_report': 'Learning Map Report',
  'assigned_user': 'Assigned User',
  'course_selected': 'Course Selected',
  'remove_course': 'Remove Course',

  'assign_users': 'Assign Users',
  'assign_users_prompt': 'Are you sure to assign users to this learning map?',
  'unassign_users_prompt': 'Are you sure you want to delete the assigned user?',
  'learning_map_assign_users': 'Learning Map Assign Users',
  'learning_map_assign_users_template': 'Learning Map Assign Users Excel Template',
  'user_list': 'User List',
  'assigned_permissions': 'Assigned Permissions',

  'select_courses': 'Select Courses',
  'loading': 'Loading',

  // certificate
  'copy_certificate_template': 'Are you sure you want to copy this certificate template?',
  'delete_certificate_template': 'Are you sure you want to delete this certificate template?',
  'create_certificate_template': 'Create Certificate Template',
  'edit_certificate_template': 'Edit Certificate Template',
  'orientation': 'Orientation',
  'landscape': 'Landscape',
  'portrait': 'Portrait',
  'background_color': 'Background color',
  'select_image': 'Select Image',
  'subject_name': 'Subject name',
  'theme_name': 'Theme name',
  'certificate_no': 'Certificate number',
  'user_address': 'User address',
  'edit_certificate_template_clear': 'Are you sure you want to clear the certificate?',
  'certificate_regenerate': 'Regenerate the certificate',
  'certificate_preview': 'Preview Certificate',
  'certificate_clear': 'Clear Certificate',
  'add_content': 'Add content',
  'certificate_template': 'Certificate Template',
  'course_name_en': 'Course Name (English)',
  'course_name_zh_hk': 'Course Name (Traditional Chinese)',
  'course_name_zh_cn': 'Course Name (Simplified Chinese)',
  'subject_name_en': 'Subject Name (English)',
  'subject_name_zh_hk': 'Subject Name (Traditional Chinese)',
  'subject_name_zh_cn': 'Subject Name (Simplified Chinese)',
  'theme_name_en': 'Theme Name (English)',
  'theme_name_zh_hk': 'Theme Name (Traditional Chinese)',
  'theme_name_zh_cn': 'Theme Name (Simplified Chinese)',
  'select_cert_temp':'Select Certificate Template',
  'no_cert_temp_selected': 'No certificate selected',

  // login
  'login_user_id_hint': 'Please enter your user ID',
  'login_password_hint': 'Please enter your password',
  'show_password': 'Show password',
  'hide_password': 'Hide password',

  'batch_actions': 'Batch Actions',

  // notification
  'push_notification': 'Push Notification',
  'push_notification_management': 'Push Notification Management',
  'course_notification': 'Course Notification',
  'notice': 'Notice',
  'push_time': 'Push Time',
  'send_failed': 'Failed',
  'waiting_to_send': 'Waiting To Send',
  'pause': 'Pause',

};
