// lang-zh-cn.ts
export const LANG_ZH_CN_NAME = 'zh_cn';

export const LANG_ZH_CN_TRANS = {

  // login
  'user_id': '用户编号',
  'user_name': '用户名称',
  'email': '电子邮件',
  'password': '密码',
  'company_id': '公司编号',
  'login': '登入',
  'language': '语言',
  'register': '注册',
  'forget_password': '忘记密码',
  'disclaimer': '声明',
  'disclaimer_message': '登录即表示您同意声明的条款。',
  'dont_have_account': '未有帳戶？',
  'click_here_create': '按此创建公司帐户',
  'internal_login': '内部登入',
  'company_login': '公司登入',
  'use_another_account': '使用另一个帐户',

  // register
  'company_full_name': '公司全名',
  'company_short_name': '公司简称',
  'required_to_fill_in': '需要填写这格',
  'confirm_password': '重新输入密码',
  'invalid_email_address': '无效的邮件地址',
  'password_not_match': '密码不相符',

  // setting
  'change_language': '更改语言',
  'change_language_alert': '你是否确定更换语言: @{}?',
  'optional': '选填',

  // timeout-box
  'timeout': '时间超过',
  'timeout_prompt': '继续使用平台',
  'time_left': '剩余时间',
  'second': '秒',
  'continue': '继续',
  'leave': '离开',

  //notification
  'notifications': '通知',
  'cert_is_ready_hint': ': 证书已可下载',
  'download_certifications': '下载证书',
  'download_report': '下載报告',

  // toast
  'ready_to_download': '准备下载',
  'download': '下载',
  'download_input': '下载@{}',
  'downloading': '下载中',
  'download_error': '下载错误',
  'download_completed': '下载完成',
  'download_waiting_prompt': '请等候下载完成后才继续',
  'unable_to_download': '无法下载',
  'error_occurred': '发生错误',
  'details': '详细内容',

  // page-not-found
  'page_not_found': '找不到页面',
  'page_not_exist': '您要查找的页面不存在',
  'previous_page_prompt': '您可以点击下面的按钮返回上一页',
  'back': '返回',
  'no_errors_found': '找不到错误',
  'close': '关闭',

  // page-no-permission
  'forbidden': '禁止',
  'access_denied': '拒绝访问',
  'no_permission_content': '您无权访问该页面',

  // layout
  'scroll_top': '置顶',
  'grid_view': '网格显示',
  'list_view': '列表显示',

  // header
  'logout': '登出',
  'welcome': '欢迎',

  // dashboard
  'dashboard': '仪表板',
  'dashboard_statistics': '数据统计',
  'dashboard_all_course_statistics': '所有课程统计',
  'dashboard_user_count': '用户人数',
  'dashboard_course_count': '课程数',
  'dashboard_login_count': '登入人数',
  'dashboard_devices': '装置',
  'dashboard_likes': '点赞数',
  'dashboard_recommendations': '推荐数',
  'dashboard_completions': '完成课程数',
  'dashboard_enrollments': '报读课程数',

  //department
  'department_id': "部门编号",
  'department_short_description': "描述 (短)",
  'department_long_description': "描述 (长)",
  "select_department": "选择部门",
  "selected_department": "部门列表",
  'self_department': "此部门",

  // course-management
  'course_management': '课程管理',
  'online_courses': '线上课程',
  'offline_courses': '线下课程',

  // user-management
  'user_management': '用户管理',
  'all_users': '全部用户',

  // subject
  'subject': '学系',
  'create_subject': '新增学系',
  'edit_subject': '编辑学系',
  'delete_subject': '删除学系',

  // theme
  'theme': '主题',
  'create_theme': '新增主题',
  'edit_theme': '编辑主题',
  'delete_theme': '删除主题',

  // actions
  'create': '新增',
  'edit': '编辑',
  'delete': '删除',
  'actions': '操作',
  'more_actions': '更多操作',
  'view': '检视',
  'search': '搜寻',
  'searching': '搜寻中',
  'save_and_next': '储存并继续',
  'skip': '跳过',
  'drag_and_reorder': '拖动并重新排序',
  'no_data_available': '无资料',
  'select': '选择',
  'item(s)': '项',
  'selected': '已选',
  'checkbox_selected': '已选择',
  'please_remove': '请移除',

  // subject-edit
  'name': '名称',
  'lang_cn_short': '简',
  'lang_hk_short': '繁',
  'lang_en_short': 'ENG',
  'lang_cn_long': '简体中文',
  'lang_hk_long': '繁体中文',
  'lang_en_long': '英语',
  'save': '储存',
  'reset': '重置',
  'cancel': '取消',
  'confirm_delete_prompt': '你是否确定要删除此项？',
  'confirm_permanently_delete_prompt': '你是否确定要永久删除此项？',

  // course-edit
  'course': '课程',
  'create_course': '新增课程',
  'edit_course': '编辑课程',
  'delete_course': '永久删除课程',
  'cover_image': '封面图片',
  'choose': '选择',

  //excel
  'browse': '浏览',
  'select_file_with_appropriate_format': '请选取拥有适当格式的档案',
  'download_excel_template': '下载Excel范本',
  'excel_template': 'Excel范本',
  'preview': '预览',
  'import_excel': '导入Excel',
  'import_by_excel': '以Excel导入',
  'excel_format_incorrect': 'Excel格式不正确',
  'excel_content_error': 'Excel内容错误',
  'excel_sheet_name_must_be': 'Excel中的表名必须是',
  'excel_sheet_name_must_have': 'Excel中的表名必须有',
  'no_excel_content': '找不到Excel内容',
  'no_relevant_information': '没有相关资料',
  'total': '总共',
  'items': '项',
  'upload_failed': '上传失败',
  'import_failed': '导入失败',
  'remarks': "备注",
  'delete_remarks': '完成Excel后请删除备注和范例',
  'fill_in_next_sheet': '请于"@{0}"页填写@{1}',
  'create_template': '新增"@{0}"Excel范本',

  //temp
  'entry_date': '入职日期',
  'account_expiry_date': '帐户有效日期',
  'user': '用戶',
  'vocab': '词汇',
  'quiz': '小测',
  'enrollment': '新增学员',

  // course
  'course_title_en': 'Event Name (English)',
  'course_title_zh_hk': 'Event Name (Traditional Chinese)',
  'course_title_zh_cn': 'Event Name (Simplified Chinese)',
  'event_code': 'Event Code',
  'course_confirm': 'Manager Confirmation (1-Yes, 0-No)',
  'public_quota': 'Seat Available',
  'enquiry_email': 'Enquiry Email',
  'course_format': 'Course completion report format (Training/ CPD Score)',
  'external_course_code': 'Course ID/ Course Code',
  'register_start_date': 'Enrollment Start Date (YYYY-MM-DD HH:mm)',
  'register_end_date': 'Enrollment Deadline (YYYY-MM-DD HH:mm)',
  'status': '状态',

  // Lesson
  'lesson': '课堂',
  'lesson_content': '课堂内容',
  'order': 'Order',
  'lesson_title': 'Lesson Title',
  'lesson_start_date': 'Lesson Start Date (YYYY-MM-DD HH:mm)',
  'lesson_end_date': 'Lesson End Date (YYYY-MM-DD HH:mm)',
  'location': 'Location',
  'course_id': '课程编号',
  'lesson_id': '课堂编号',
  'lesson_info': '课堂资料',
  'lesson_material': '課堂教材',
  'lesson_and_materials': '课堂 & 教材',
  'edit_lesson': '编辑课堂',
  'delete_lesson': '永久删除课堂',

  // Material
  'material': '教材',
  'view_material': '检视教材',
  'add_material': '新增教材',
  'edit_material': '编辑教材',
  'delete_material': '永久删除教材',
  'add_attachment': '新增档案',
  'add_scorm': '新增SCORM',
  'add_link': '新增链接',
  'add_activity': '新增活动',
  'view_activity': '检视活动',
  'edit_activity': '编辑活动',
  'attachment': '档案',
  'activity': '活动',
  'link': '链接',
  'hyperlink': '链接',
  'scorm': 'Scorm',
  'completion_criteria': '完成标准',
  'completed_when_opened': '开启后即完成',
  'read_pdf_to_first': '阅读PDF至开头',
  'read_pdf_to_last': '阅读PDF至最后',
  'watch_video_to_first': '影片开始后',
  'watch_video_to_last': '影片结束前',
  'submit_activity': '提交活动',
  'Page': '页',
  'page': '页',
  'visible': '可见',
  'mark_visible': '標記為可可见',
  'mark_invisible': '标记为不可见',
  'compulsory': '必修',
  'stream_pending': '等候转换中',
  'stream_generating': '转换中',
  'stream_done': '已完成',
  'stream_failed': '失败',
  'store_attachment': '储存档案',
  'update_attachment_language': '更新档案语言',
  'store_scorm': '储存SCORM',
  'material_empty_file': '课堂材料中包含空的课堂档案',
  'material_empty_link': '课堂材料中包含空的链接',
  'material_link_no_http': '链接必须包含"http"或"https"字眼',
  'others': '其他',
  'download_file': '下载档案',
  'open_hyperlink': '开启链接',
  'Second': '秒',
  'second_': '秒',
  'setting_completion_criteria': '设定完成标准',
  'lesson_files': '课堂档案',
  'scorm_popup_blocked': '我们尝试在新视窗打开SCORM，但弹出式视窗已被封锁。请允许这网站的弹出式视窗',
  'preview_scorm': '预览SCORM',
  'downloadable': '可下载',
  'non_downloadable': '不可下载',
  'set_as_downloadable': '设定为用户可下载',
  'set_as_non_downloadable': '设定为用户不可下载',

  // Activity
  'mcq': '选择题',
  'keyword': '关键词',
  'drawing': '绘图',
  'open_ended': '开放式问题',
  'video': '影片',
  'audio': '音频',
  'assignment': '作业',
  'activity_name': '活动名称',
  'activity_intro': '活动简介',
  'background_image': '背景图片',
  'tag': '标签',
  'add_tag': '新增标签',
  'add_tag_hint': '不能多于6个标签',
  'confirm_update_activity': '你是否确定更新此活动? 更改内容后，之前的所有资料将被清除。',

  // Scorm
  'version': '版本',
  'accepted_scorm_version': '仅接受Scorm版本1.2和2004',

  // Discussion
  'discussion': '讨论',
  'topic': '主题',
  'topics': '主题',
  'start_discussion': '开始讨论',
  'create_topic': '创建主题',
  'reply': '回覆',
  'like': '赞好',
  'unlike': '取消赞好',
  'delete_topic': '永久删除讨论主题',
  'confirm_delete_topic': '你是否确定要永久删除此讨论主题?',
  'delete_reply': '永久删除回覆',
  'confirm_delete_reply': '你是否确定要永久删除此回覆?',
  'edit_topic': '编辑讨论主题',
  'edit_reply': '编辑回覆',
  'choose_topic': '选择讨论主题',
  'image_attachment': '图片附件',
  'content': '內容',
  'pin_topic': '置顶讨论主题',
  'unpin_topic': '取消置顶讨论主题',
  'pin_reply': '置顶回覆',
  'unpin_reply': '取消置顶回覆',

  // Quiz
  'create_course_quiz': '创建课程小测',
  'create_lesson_quiz': '创建课堂小测',
  'edit_quiz': '编辑小测',
  'delete_quiz': '永久删除小测',
  'quiz_title': '小测标题',
  'passing_mark': '合格题数',
  'need_time_limit': '需要限时',
  'time_limit': '限时',
  'random_select_questions': '随机抽选题目',
  'number_of_questions': '抽选题数',
  'show': '显示',
  'dont_display': '不显示',
  'display_correct_answer': '作答后显示正确答案',
  'display_answer_type': '显示答案类型',
  'display_all_answer': '显示所有答案',
  'display_wrong_only': '只显示错误答案',
  'display_mc_remarks': '多选题选项显示备注',
  'allow_redo': '允许重做',
  'allow': '允许',
  'not_allow': '不允许',
  'fail_requires_retake': '不合格需要重读',
  'number_of_fails': '不合格次数',
  'total_number_of_question': '总题数',
  'new_mc_question': '新增多选题',
  'new_cloze_question': '新增填充题',
  'mc_question': '多选题题目',
  'cloze_question': '填充题题目',
  'max_choices': '最多选择答案数目',
  'title': '标题',
  'question': '题目',
  'answer': '答案',
  'option': '选项',
  'new_question': '新增题目',
  'new_option': '新增选项',
  'correct_answer': '正确答案',
  'remark': '备注',
  'explanation': '解释',
  'confirm_edit_quiz': '你是否确定要更改此小测？',
  'edit_quiz_hint': '有关小测的所有资料(包括已提交的资料)将会被重置',
  'confirm_delete_quiz': '你是否确定要永久删除此小测？',
  'import_multiple_quizzes_error': '小测不可导入多于一个题库',
  'quiz_no_questions': '小测没有题目',
  'pass_mark_exceed_total': '合格题数不可多于题目数目',
  'no_random_question': '没有抽选题数',
  'random_question_exceed_total': '抽选题数不可多于题目数目',
  'pass_mark_exceed_random': '合格题数不可多于抽选题数',
  'please_input_valid_value': '请输入有效数值',
  'max_choices_error': '最多选择答案数目不可少于1或正确答案数目及多于选项数目',
  'no_answers_error': '请选择多选题的正确答案',
  'quiz_report': '小测报告',
  'download_quiz_report': '下载小测报告',
  'need_until_correct': '需要完全正确才能完成',
  'time': '时间',
  'pages': '页',
  'show_video': '显示影片',
  'hide_video': '隐藏影片',

  // Offline course
  'offlineCourse_courseEvent': '线下课程活动',

  // File Picker
  'select_file': '选择档案',
  'my_computer': '我的电脑',
  'internet': '互联网',
  'drag_and_drop': '请将档案拖放到此处',
  'or': '或',
  'upload_by_url_hint': '请输入档案的URL',
  'upload_by_google_hint': '透过Google Drive选取档案',
  'connect_to_google_drive': '连结Google Drive',
  'select_more': '选取更多',
  'reselect': '重新挑选',
  'upload': '上传',
  'clear': '清空',
  'type': '类型',
  'size': '大小',
  'file_not_found': '未能找到档案',
  'only_accept_file_type': '只接受下列档案类型：',
  'one_file_selected_only': '只可选择一个档案',
  'load_image_failed': '载入图片失败',
  'cropping_image': '裁剪图像',
  'crop': '剪裁',
  'apply': '套用',
  'zoom_in': '放大',
  'zoom_out': '缩小',
  'rotate': '旋转',
  'auto_padding': '自动填充',
  'remove_padding': '移除填充',
  'imageLimitHint': '只能上传不多于@{}的图片',
  'fileLimitHint': '只能上传不多于@{}的档案',
  'videoLimitHint': '只能上传不多于@{}的影片',

  // course-view
  'course_and_lessons': '课程 & 课堂',
  'course_settings': '课程设定',
  'delete_course_hint': '你是否确定要永久删除此课程？',
  'permission_settings': '权限设定',
  'compulsory_settings': '必修设定',
  'enrollment_status': '报读情况',
  'course_quiz': '课程小测',
  'lesson_quiz': '课堂小测',
  'evaluation': '问卷',
  'course_certificate': '课程证书',
  'create_lesson': '新增课堂',
  'published': '已发布',
  'unpublished': '未发布',
  'confirm_unpublish_course': '你是否确定取消发布此课程？',
  'confirm_publish_course': '你是否确定发布此课程？',

  // Upload progress
  'upload_progress': '上传进度',
  'minimize_window': '缩小视窗',
  'maximize_window': '放大视窗',
  'estimating_time': '正在预测剩余时间...',
  'completed': '完成',
  'upload_succeed': '上传成功',
  'pending': '待办',

  // Upload progress
  'download_progress': "下载进度",
  'download_succeed': '下载成功',
  'download_failed': '下载失败',

  // course-edit
  'description': '简介',
  'twoFA': '两步骤验证',
  'yes': '是',
  'no': '不是',
  'continual_identity_auth': '连续身份认证',
  'biometric': '生物识别',
  'google_auth': 'Google Auth',
  'have': '有',
  'has': '有',
  'have_yes': '有',
  'have_no': '没有',
  'course_duration': '课程时间',
  'mins_short': '分',
  'minutes': '分钟',
  'seconds': '秒',
  'enabled': '已启用',
  'disabled': '已停用',
  'multi_lang_missing_title_hint': '请填写名称',
  'multi_lang_missing_description_hint': '请填写简介',
  'multi_lang_missing_cover_hint': '请选择封面图片',
  'customize_image': '自订图片',
  'new': '新增',
  'change_image': '更改图片',
  'course_point': '课程点数',
  'access_days_limit': '访问日数限制',

  // user-list
  'add_user': '新增用户',
  'department': '部门',
  'job_rank': '职级',
  'view_and_edit': '检视 & 修改',
  'activated': '启用中',
  'deactivated': '已终止',
  'item_per_page': '每页:',
  'next_page': '下一页',
  'previous_page': '上一页',
  'activation_title': '用户状态更改',
  'activation_content': '是否确定更改以下用户的状态为',
  'restore': '恢复',
  'confirm': '确定',
  'icon': '头像',
  'locked_status': '用户状态',
  'activate_user': '启用已选择用户',
  'deactivate_user': '终止已选择用户',
  'approve_user': '核准用户',
  'approve_selected_user': '核准已选择用户',
  'reject_selected_user': '拒絕已選擇用戶',
  'cp_allocation': '课程点数分配',
  'current_cp': '现有课程点数',
  'cp_to_selected_users': '分配指定数目课程点数至已选择用户',
  'required_cp': '此转移所需的课程点数',
  'remain_cp': '此转移后剩余的课程点数',
  'transfer_cp': '转移课程点数',
  'cp_amount_min_error': '数值不可以少于1',
  'cp_amount_not_enough': '公司没有足够的课程点数',
  'select_dept': '选择部门',
  'confirm_user_data': '确认您的输入',

  //user-view
  'external_id': '用户编号',
  'basic_info': '基本信息',
  'course_info': '课程信息',
  'permission_info': '权限信息',
  'user_title': '职级',
  'change_password_hint': '需要更改才输入',
  'user_report': '用戶报告',
  'create_user': '新增用户',
  'profile': '用户信息',
  'compulsory_courses': '必修课程',
  'non-compulsory': '选修课程',
  'recommended': '推荐课程',
  'pass': '合格',
  'achievements': '成就',
  'user_course_data': '用户课程数据',
  'completed_courses': '已完成课程',
  'in_progress_courses': '进行中课程',
  'valid_password_alert_msg': '请输入有效的密码',


  //user-view-course-info
  'subject_title': '学系',
  'theme_title': '主题',
  'course_title': '报读课程名称',
  'pivot_start_date': '开始时间',
  'completion_status': '完成情况',
  'pivot_end_date': '完成时间',
  'has_quiz': '小测',
  'not_yet_assessed': '不设小测',
  'no_assessment': '未考核',
  'certificate': '证书',

  //user-admin-list
  'add_admin': '新增管理员',
  'admin_permission': '管理员权限',
  'user_employed': '在职',
  'admin_user_list': '管理员列表',
  'create_user_admin': '新增管理员',
  'update_user_admin': '更新管理员',
  'role_title': '权限范本',
  'role_titles': '权限范本',
  'permission': '权限',
  'viewable_department_titles': '部门管理权限',
  'role_list': '权限范本列表',
  'create_role': '新增权限范本',
  'update_role': '更新权限范本',
  'new_role': '新权限范本',
  'delete_role': '永久删除权限范本',
  'delete_role_hint': '你是否确定要永久删除此权限范本？',
  'all_permissions': '所有权限',
  'role_name_incorrect': '请使用其他名称',
  'role_name_letter_incorrect': '请使用字母、数字或空格',
  'admin_step1': '选择用户',
  'admin_step2': '添加权限范本',
  'admin_step3': '添加部门管理权限',
  'admin_update_step2': '更新权限范本',
  'admin_update_step3': '更新部门管理权限',
  'select_roles': '选择权限范本',
  'admin_other_roles': '其他权限范本',
  'user_current_department': "所属部门",

  //user-admin-role-table
  'User Management': '用户管理',
  'Manage Reports': '报告管理',
  'Company Management': '公司管理',
  'Unit Management': '单位管理',
  'Login CMS': '可登入CMS',
  'Login Teacher website': '可登入面授平台',
  'Manage users': '监视用户',
  'Admin permission': '管理员权限',
  'Department Management': '部门管理',
  'overall_course_report': '整体课程报告',
  'course_participation_report': '课程参与报告',
  'course_completion_report': '课程完成报告',
  'overall_user_report': '整体用户报告',
  'user_individual_report': '用户单独报告',
  'overall_user_login_report': '整体用户登入报告',
  'Push Notification': '推送通知',
  'Banner': '横幅',
  'Highlight Management': '专区管理',
  'Highlight Topic Management': '专题管理',
  'Mock Exam': '模拟考试',
  'Discussion': '讨论',
  'Learning Map': '学习地图',
  'Course Certificate': '课程证书',
  'Vocabulary': '词汇',
  'Offline Courses': '线下课程',
  'Material Library': '资源库',
  'System Management': '系统管理',
  'Manage Units': '公司管理',
  'Manage Plans': '计划管理',
  'Manage Products': '产品管理',
  'Trainer Management': '导师管理',

  // image-viewer
  'no_image_found': '找不到图片',

  // Qti
  'qti_format': 'QTI格式',
  'about_qti': 'QTI简介',
  'import_qti': '导入QTI',
  'import_by_qti_format': '以QTI格式导入小测',
  'download_qti': '下載QTI格式的小测',
  'accept_qti_version': '仅接受QTI版本2.0, 2.1, 2.2',
  'qtiQuiz': 'QTI小测',
  'qti_quiz': 'QTI小测',
  'add_qti_quiz': '新增QTI小测',
  'submit_quiz': '提交小测',
  'test_id': '小测编号',
  'store_qti_quiz': '储存QTI小测',
  'download_qti_quiz': '下载QTI小测档案',
  'preview_qti_quiz': '预览QTI小测',
  'qti_intro': 'QTI简介',
  'supported_version': '支援版本',
  'supported_question_type': '支援题型',
  'qti_quiz_tutorial': '制作QTI小测教学',
  'qti_intro_paragraph_1': 'IMS问题与测试互操作性规范（QTI）定义了表示评估内容和结果的标准格式，支持在创作和交付系统，存储库和其他学习管理系统之间交换此材料。 它允许编写评估材料，并可以在多个系统上互换使用。 因此，它旨在促进系统之间的互操作性。',
  'qti_intro_paragraph_2': '该规范包括一个数据模型，该模型定义问题，评估和问题及评估结果的结构，以及XML数据绑定，该XML数据绑定实质上定义了用于交换问题和其他评估材料的语言。 XML绑定被广泛用于在不同的创作工具之间以及由发布者交换问题。 规范的评估和结果部分使用较少。',
  'support': '支援',
  'suggest': '建议',
  'question_type': '题型',
  'mobile': '轻触式',
  'desktop': '电脑',
  'qti_more_detail': '欲知更多，请参考以下连结',
  'qti_structure_paragraph_1': '制作一个QTI小测，需要上传一个.zip档案的包裹，当中包含.xml格式的test, part, section, item，以及item所需的各种素材。起始档案必需命名为index.xml，并必需包含assessmentTest的标签，否则系统无法读取。',

  // multi-lang-basic
  'primary_language': '主要语言',
  'update': '更新',

  // search-box
  'search_add': '新增项目',

  // course-setting
  'quiz_will_be_deleted': '小测将被删除',
  'evaluation_will_be_deleted': '问卷将被删除',
  'confirm_multi_delete': '你是否确定要删除: @{}?',
  'delete_hint': '所有资料(包括已提交的资料)将会被删除',

  // evaluation-edit
  'confirm_delete_evaluation': '你是否确定要删除问卷?',
  'delete_evaluation': '删除问卷',
  'confirm_edit_evaluation': '你是否确定要更改问卷内容？',
  'edit_evaluation_hint': '有关此问卷的所有资料(包括已提交的资料)将会被重置',
  'evaluation_title': '问卷标题',
  'import_template': '导入预设问题',
  'section_title': '章节标题',
  'delete_section': '删除章节',
  'new_section': '新增章节',
  'score_question': '比分题题目',
  'lowest_display_text': '最低分显示文字',
  'highest_display_text': '最高分显示文字',
  'score_question_range': '分数范围',
  'open_ended_question': '自由题目',
  'new_score_question': '新增比分题',
  'new_open_ended_question': '新增自由题',
  'evaluation_no_sections': '问卷没有章节',
  'question_required': '至少需要一个问题',
  'options_required': '至少需要两个选择',
  'edit_evaluation_template': '编辑默认问题',
  'create_evaluation_template': '新增默认问题',
  'save_template': '保存默认问题',
  'cancel_template': '取消默认问题',
  'delete_template': '删除默认问题',
  'confirm_edit_evaluation_template': '你是否确定要更改默认问题内容?',
  'confirm_create_evaluation_template': '你是否确定要新增默认问题内容?',
  'confirm_delete_template': '你是否确定要删除默认问题?',
  'confirm_cancel_edit_evaluation_template': '你是否确定要取消更改默认问题内容?',
  'confirm_cancel_create_evaluation_template': '你是否确定要取消新增默认问题内容?',
  'confirm_cancel_edit_evaluation': '你是否确定要取消更改问卷内容?',
  'save_succeed': '保存成功',

  // course-enrollment
  'course_enrolled_users': '已报读用户',
  'course_new_enrollment': '新增报读用户',
  'course_enroll_users': '课程报读用户',
  'start_time': '开始时间',
  'completion_time': '完成时间',
  'not_yet_completed': '尚未完成',
  'ok': '知道了',
  'reorder': '重新排序',
  'move_up': '向上移动',
  'move_down': '向下移动',
  'course_name': '课程名称',
  'search_result': '搜寻结果',
  'clear_search_result': '清除搜寻结果',
  'total_num_result_text': '共@{} 项结果',
  'delete_enrolled_user_prompt': '你是否确定要删除已报读用户?',
  'view_user': '检视用户',
  'expiry_date': '到期日',

  // mock-exam
  'mockexam': '模拟考试',
  'mockexam_management': '模拟考试管理',
  'create_mockexam': '新增模拟考试',
  'number_of_completions': '完成人数',
  'qualified_number': '合格人数',
  'average_score': '平均分',
  'edit_mockexam_confirm': '你是否确定要更改模拟考试？',
  'delete_mockexam_confirm': '你是否确定要删除模拟考试',
  'delete_mockexam_hint': '有关此模拟考试的所有资料(包括已提交的资料)将会被删除。',
  'publish_mockexam_confirm': '你是否确定发布此模拟考试？',
  'unpublish_mockexam_confirm': '你是否确定取消发布此模拟考试？',
  'cannot_edit_published_mockexam': '不能更改已发布的模拟考试',
  'cannot_delete_published_mockexam': '不能删除已发布的模拟考试',
  'publish': '发布',
  'section': '章节',
  'create_section': '新增章节',
  'required': '需要填写',

  // question-bank
  'question_bank': '试题库',
  'create_question_bank': '新增试题库',
  'edit_question_bank_confirm': '你是否确定要更改试题库？',
  'delete_question_bank_confirm': '你是否确定要删除试题库',
  'delete_question_bank_hint': '有关此试题库的所有资料（包括模拟考试中已提交的资料）将会被删除。',
  'import_multiple_question_bank_error': '不可导入多于一个试题库',

  // download-excel-template-btn
  'excel_remarks_sample_sheet': '这是范例页, 请于 @{} 页填写资料',

  // quiz-basic
  'import_quiz_template': '导入小测Excel范本',
  'excel_remarks_one_quiz': '此表格只允许导入一个小测, 请在 Title 中填写相同的标题',
  'excel_remarks_mc_question': '如果这是选择题, 请在 Answer 中填写选项编号',
  'excel_remarks_fill_question': '如果这是填充题, 请在 Answer 中填写正确答案并不需填写 MC Option 栏',

  // question-bank
  'import_question_bank_template': '导入试题库Excel范本',
  'excel_remarks_one_question_bank': '此表格只允许导入一个题库, 请填写相同的标题和简介',
  'excel_remarks_mc_question_option': '请在 Answer 中填写选项编号',
  'excel_remarks_same_question_bank': '如果问题在同一个题库, 请填写相同的题目和简介',

  // banner
  'home_page': '首页',
  'banner': '横幅',
  'banners': '横幅',
  'login_banners': '登入横幅',
  'banner_management': '横幅管理',
  'login_banner_management': '登入横幅管理',
  'create_banner': '新增横幅',
  'create_login_banner': '新增登入横幅',
  'edit_banner': '编辑横幅',
  'delete_banner': '删除横幅',
  'delete_banner_confirm': '你是否确定要删除此横幅?',
  'website_url': '网址',
  'banner_status': '状态',
  'no_banner': '没有横幅',
  'reorder_confirm': '储存排序?',

  // highlight
  'highlight_management': '专区管理',
  'highlight': '专区',
  'create_highlight': '新增专区',
  'edit_highlight': '编辑专区',
  'delete_highlight': '删除横幅专区',
  'create_highlight_topic': '新增专题',
  'edit_highlight_topic': '编辑专题',
  'delete_highlight_topic': '删除专题',

  // course-view
  'leave_page_hint': '你是否确定要离开此页面?',
  'leave_page_desc': '系统将不会储存您所做的变更',

  //unit
  'unit_management': '单位管理',
  'create_unit': '新增单位',
  'update_unit': '更新单位',
  'unit_id': '单位编号',
  'new_unit': '新单位',
  'unit_list': '单位列表',
  'unit': '单位',
  'unit_info': '单位资料',
  'unit_user': '单位成员',
  'unit_admin': '单位管理员',
  'add_unit_user': '新增单位成员',
  'add_unit_admin': '新增单位管理员',
  'short_description': "描述 (短)",
  'long_description': "描述 (长)",
  'unit_missing_short_description': '请填写描述 (短)',
  'unit_missing_long_description': '请填写描述 (长)',
  'unit_delete_hint': '你是否确定要删除此单位?',
  'unit_delete_admin_hint': '你是否确定要删除这些单位管理员?',
  'approved': '已核准',
  'unit_approve_hint': '你是否确定核准此单位?',
  'unit_unapprove_hint': '你是否确定取消核准此单位?',
  'default_unit_not_editable': '不可以更改默认单位',

  //department
  'department_management': '部门管理',
  'department_name': '部门名称',
  'department_parent_id': '上级部门编号',
  'department_parent_long_description': '上级部门名称',
  'create_department': '新增部门',
  'update_department': '更新部门',
  'new_department': '新部门',
  'department_delete_hint': '你是否确定要删除此部门?',
  'department_missing_external_id': '请填写部门编号',
  'parent_department': '上级部门',
  'department_manager': '部门经理',
  'add_department_manager': '选择部门经理',
  'add_department_parent': '选择上级部门',
  'duplicated_department_external_id_hints': '部门编号已被使用，请输入有效的部门编号',
  'department_cannot_delete_hint': '未能刪除此部門',
  'department_has_manager_hint': '部门经理',
  'department_has_children_hint': '子部门',

  //widget-table
  'filter_columns': '筛选栏列',

  // course-enrollment-dialog
  'select_user': '选择用户',
  'edit_list': '编辑列表',
  'next_step': '下一步',
  'previous_step': '返回',

  // course-compulsory
  'confirm_delete_selected_prompt': '你是否确定要删除已选择的项目?',
  'compulsory_due_date': '到期日',
  'compulsory_users': '必修用户',
  'add_compulsory_users': '新增必修用户',
  'compulsory_departments': '必修部门',
  'add_compulsory_departments': '新增必修部门',
  'import_user_template': '导入用户Excel范本',

  'course_reminder': '课程提醒',
  'send_course_reminder': '发送课程提醒',
  'not_completed_users': '所有未完成课程的用户',
  'course_compulsory_reminder': '系统将在完成日期的@{}天之前自动发送提醒',
  'sending': '发送中',
  'sent': '已发送',

  // user-abilities-setting
  'user_permission': '用户权限',
  'admin_permission_settings': '管理员权限设定',

  // course-permission
  'default_permissions': '默认权限',
  'has_permission_list': '有权限列表',
  'no_permission_list': '没有权限列表',
  'has_permission': '有权限',
  'no_permission': '没有权限',
  'add_permissions': '新增权限',
  'cancel_permission': '取消权限',
  'change_default_permissions_propmt': '你是否确定要更改默认权限?',
  'cancel_permissions_propmt': '你是否确定要取消已选择项目的权限?',
  'cancel_existing_permissions': '取消现有权限',
  'existing_permissions': '现有权限',
  'add_input': '新增@{}',
  'create_input': '新增@{}',
  'edit_input': '编辑@{}',
  'change_input': '更改@{}',
  'add_items': '新增项目',
  'select_item': '选择项目',
  'select_job_rank': '选择职级',
  'join_date': '入职日期',
  'selected_date': '已选择日期',
  'from': '从',
  'to': '到',

  //trainer
  'trainer': '导师',
  'trainers': '导师',
  'trainer_managemnet': '导师管理',
  'create_trainer': '新增导师',
  'edit_trainer': '编辑导师',
  'remove_trainer': '移除导师身份',
  'trainer_description': '导师简介',
  'remove_trainer_role_confirm': '你是否确定要移除用户导师身份？',
  'avatar': '头像',
  'add_trainer_description': '加入导师简介',

  // product
  'product': '产品',
  'products': '产品',
  'product_management': '产品管理',
  'create_product': '新增产品',
  'edit_product': '编辑产品',
  'delete_product': '删除产品',
  'view_product': '检视产品',
  'duplicate_product': '複製產品',
  'seat': '座位',
  'storage': '储存空间',
  'free': '免费',
  'user_shop': '用戶商店',
  'company_shop': '公司商店',
  'price': '价钱',
  'currency': '货币',
  'delete_product_confirm': '你是否确定要删除此产品？',
  'activate_product_confirm': '你是否确定要启用此产品？',
  'deactivate_product_confirm': '你是否确定要停用此产品？',
  'product_info': '产品资讯',
  'web_platform': '网页平台',
  'ios_platform': 'iOS平台',
  'android_platform': 'Google Pay平台',
  'purchase': '购买',
  'purchase_product': '购买产品',

  // income report
  'income_report': '收入报告',
  'stripe_transaction': '经Stripe付款',
  'ios_transaction': '经iOS付款',
  'android_transaction': '经Android付款',
  'count': '数量',
  'amount': '金额',
  'stripe_processing_fee': 'Stripe交易手续费',
  'stripe_processing_fee_hint': '(基本: 3.4% + HK$2.35)',
  'ios_fee': 'iOS费用',
  'android_fee': 'Android费用',
  'final_net': '最终净赚',
  'each': '每项',
  'cp_transaction': '使用课程点数付款',
  'cp_fee': '课程点数手续费',

  // transaction
  'income_records': '收入记录',
  'date': '日期',
  'customer': '顾客',
  'fee': '费用',
  'net': '净赚',
  'platform': '付费平台',
  'coupon': '优惠码',
  'refund': '退款',
  'refund_type': '退款方式',
  'no_refund': '不退款',
  'refunded_by_hkd': '已以港币退款',
  'refund_by_cp': '以课程点数退款',
  'refund_amount': '退款金额',
  'withdraw_resources': '收回资源',
  'ban_access_to_course': '禁止访问课程',

  // system
  'system': '系统',
  'system_management': '系统管理',

  // user-abilities
  'all_course_permissions': '所有课程权限',
  'create_quiz': '新增小测',
  'view_quiz_report': '查看小测报告',
  'create_evaluation': '新增问卷',
  'view_evaluation_report': '查看问卷报告',
  'view_discussion': '检视讨论',
  'set_permissions': '设置权限',
  'remove_course_abilities_disabled_hint': '请于@{}级别移除此用户的权限',
  'remove_course_abilities': '移除权限',
  'no_selected_permission_hint': '请至少选择一项权限',
  'change_all_ability_hint': '请于管理员权限页面更改权限',
  'view_only': '只可检视',
  'editor': '可编辑',
  'save_course_abilities_prompt': '你是否确定要储存管理员权限?',

  // evaluation
  'evaluation_report': '问卷报告',
  'download_evaluation_report': '下载问卷报告',
  'incorrect_content': '内容不正确',
  'settings': '设定',

  // reports
  'reports': '报告',
  'course_reports': '课程报告',
  'user_reports': '用户报告',
  'system_data': '系统数据',
  'num_enrollment': '报读人数',
  'num_finished_users': '完成人数',
  'course_hours': '课程学时 (小时)',
  'all_courses': '所有课程',
  'created_date': '创建日期',
  'updated_date': '更新日期',
  'num_lessons': '课堂数目',
  'assessment_method': '考核方式',
  'filter_course_report': '筛选课程报告',
  'all_courses_report': '整体课程报告',
  'all_users_report': '整体用户报告',
  'department_report': '部门报告',
  'login_report': '用户登入报告',
  'recommendation_report': '推荐报告',
  'course_report': '课程报告',
  'report_is_ready_hint': ' 已准备好下载。',

  'hr_status': 'HR状态',
  'recommended_count': '被推荐课程数',
  'enrolled_courses_count': '报读课程数',
  'completed_courses_count': '完成课程数',
  'passed_courses_count': '合格课程数',
  'likes_count': '点赞课程数',
  'user_expiry': '离职日期',
  'filter_user_report': '筛选用户报告',
  'year': '年',
  'month': '月',
  'day': '日',

  // months
  'month_1': '一月',
  'month_2': '二月',
  'month_3': '三月',
  'month_4': '四月',
  'month_5': '五月',
  'month_6': '六月',
  'month_7': '七月',
  'month_8': '八月',
  'month_9': '九月',
  'month_10': '十月',
  'month_11': '十一月',
  'month_12': '十二月',

  'select_all': '选择全部',
  'unselect_all': '取消选择全部',
  'select_hint': '请选择',
  'select_all_search_result': '选择全部搜寻结果',
  'unselect_all_search_result': '取消选择全部搜寻结果',
  'login_report_disabled_hint': '请选择年和月',

  // Zoom Meeting
  'add_zoom_meeting': '新增Zoom会议',
  'edit_zoom_meeting': '编辑Zoom会议',
  'zoom_input_meeting': '输入现有Zoom会议',
  'zoom_create_meeting': '创建新的Zoom会议',
  'zoom_meeting_title': '会议名称',
  'zoom_meeting_description': '会议简介',
  'zoom_meeting_id': '会议 ID',
  'zoom_meeting_start_date': '会议开始日期和时间',
  'zoom_duration': '会议时长',
  'zoom_password_hint': '最多 10 个字符',
  'view_zoom_meeting': '检视Zoom会议',
  'open_zoom_meeting': '打开Zoom会议連結',
  'zoom_not_enabled': '不支持连接到 Zoom 帐户。',
  'zoom_oauth_message_title': '需要Zoom账号授权！',
  'zoom_oauth_message_content': '请完成弹出连结中的步骤，完成授权后点击「确定」。',
  'Zoom Meeting': 'Zoom会议',
  'zoom_meeting': 'Zoom会议',
  'zoom_install_title': '连接您的 Zoom 帐户',
  'zoom_install_first': '如果您希望将Zoom帐户连接到iTrain，请点击 ',
  'here': '这里',
  'zoom_install_second': ' 完成授权。',
  'zoom_uninstall_first': '您可以随时于',
  'zoom_uninstall_second': '取消连接。',
  'zoom_not_allowed_to_update': '此 Zoom 会议只能由其创建者(@{})编辑。',

  'no_subject': '没有学系',
  'no_theme': '没有主题',
  'no_course': '没有课程',
  'no_lesson': '没有课堂',

  // course-statistics
  'course_statistics': '课程数据',
  'course_creation_date': '课程创建日期',
  'last_update_time': '最后更新时间',
  'start_date': '开始日期',
  'end_date': '结束日期',
  'all': '全部',
  'this_month': '本月',
  'this_quarter': '本季',
  'this_year': '本年',

  'num_completion': '完成人数',
  'num_incompletion': '未完成人数',
  'overall_num_enrollment': '总报读人数',
  'overall_num_completion': '总完成人数',

  // verify email
  'verification_code': '验证码',
  'verify': '验证',
  'verify_email': '验证你的电邮',
  'verify_email_hint': '我们刚刚通过您的电子邮件向您发送了验证码。',
  'verify_failed': '验证码不正确。',
  'verify_succeed': '验证成功。',
  'dont_receive_code': '尚未接收到验证码？',
  'has_been_resent': '已重发，请检查',
  'next_resend': '下次重发机会：',
  'resend': '重新发送',

  // company
  'company_management': '公司管理',
  'company_info': '公司资讯',
  'usage': '用量',

  // subscription
  'subscription': '订阅',
  'subscription_info': '订阅资讯',
  'current_plan': '当前计划',
  'next_plan': '下个计划',
  'plan_title': '计划名称',
  'plan_description': '计划简介',
  'period': '订阅期',
  'paid_by': '付款人',
  'subscribe': '订阅',
  'active': '服务生效中',
  'incomplete': '未完成付款',
  'incomplete_expired': '未完成付款并过期',
  'trialing': '试用中',
  'past_due': '过期',
  'canceled': '已取消',
  'unpaid': '未付款',
  'unsubscribe': '退订',
  'resume_subscription': '恢复订阅',
  'change_plan': '更换计划',
  'unsubscribe_confirm': '您是否确定要退订目前计划？',
  'unsubscribe_succeeded': '已成功退订',
  'resume_subscription_confirm': '您是否确定要恢复订阅？',
  'resume_subscription_hint': '这动作会取消已订阅的计划',
  'resume_subscription_succeeded': '恢复订阅成功',
  'unsubscribed': '已退订',
  'service_end_at': '服务终结日',
  'upgrade_now': '即時升級',
  'change_plan_period_end': '当前计划结束后更换',
  'scheduling_next_plan': '安排下一个计划',
  'next_plan_scheduled': '下一个计划已安排',
  'subscription_change_and_charge_at': '您的订阅会在这时间后自动更换计划及收费',
  'cancel_scheduled_subscription': '取消订阅计划',
  'cancel_scheduled_subscription_confirm': '您是否确定要取消订阅计划？',
  'cancel_scheduled_subscription_succeeded': '已取消订阅计划',

  // payment
  'add_payment_method': '新增付款方法',
  'cancel_payment': '取消付款',
  'card': '信用卡',
  'card_data': '信用卡资料',
  'card_number': '信用卡号码',
  'charge_id': '收费编号：',
  'confirm_3ds': '验证3D-Secure',
  'confirm_payment': '确认付款',
  'coupon_code': '优惠码',
  'coupon_discount_less_hint': '优惠码折扣少于 1 个课程点数。 此优惠码无效。',
  'error_code': '错误码',
  'failed': '失败',
  'incomplete_cvc': '您的信用卡安全码并不完整。',
  'incomplete_expiry': '您的信用卡到期日不完整。',
  'incomplete_number': '您的信用卡号码不完整。',
  'incomplete_payment': '未完成付款程序',
  'invalid_coupon': '优惠码无效',
  'invalid_expiry_month_past': '您的信用卡已过期。',
  'invalid_expiry_year_past': '您的信用卡已过期。',
  'invalid_number': '您的卡号无效。',
  'payment': '付款',
  'payment_': '付款 ',
  'payment_date': '日期：',
  'payment_failed': '付款失败',
  'payment_pending': '等待付款',
  'payment_succeeded': '付款成功',
  'pending_3ds': '等待3D-Secure验证中',
  'receipt': '收据',
  'receipt_number': '收据编号：',
  'refunded': '已退款',
  'remove_card_confirm': '您是否确定要从电子银包中移除此信用卡？',
  'save_card_data': '保存我的信用卡资料',
  'saved_card': '已储存的信用卡',
  'select_payment_method': '选择付款方法',
  'start_course': '开始课程',
  'succeeded': '成功',
  'view_receipt': '查看收据',
  'confirm_price': '确定价钱',
  'result': '结果',
  'view_invoice': '查看发票',
  'download_invoice': '下载发票',
  'cancel_subscription': '取消订阅',
  'skip_auth': '跳过认证',
  'cancel_incompleted_subscription_confirm': '您是否确定要取消此未完成订阅？',
  'cancel_incompleted_subscription_succeeded': '已成功取消此未完成订阅',
  'new_plan': '新计划',
  'remain_time_value': '剩余的时间价值',
  'unused_time_value': '未用完的时间价值',
  'coupon_applied': '优惠码已启用',

  // shop
  'shop': '商店',

  // transaction
  'transaction': '交易纪录',
  'action': '动作',
  'swap_subscription': '更换订阅计划',
  'renew_subscription': '续订',
  'transfer': '转移',
  'void': '空白',
  'pay': '付款',
  'my_transaction': '我的交易纪录',
  'my_transaction_hint': '付款及交易纪录',

  // company setting
  'setting': '设定',

  // product
  'plan': '计划',
  'plans': '计划',
  'plan_management': '计划管理',
  'create_plan': '新增计划',
  'edit_plan': '编辑计划',
  'delete_plan': '删除计划',
  'view_plan': '检视计划',
  'duplicate_plan': '复制计划',
  'delete_plan_confirm': '你是否确定要删除此计划？',
  'activate_plan_confirm': '你是否确定要启用此计划？',
  'deactivate_plan_confirm': '你是否确定要停用此计划？',
  'plan_info': '计划资讯',
  'interval': '时限',
  'interval_unit': '时限单位',
  'interval_count': '时限数',
  'years': '年',
  'months': '月',
  'days': '日',
  'access_level': '访问权限',

  // dollar
  'hkd': 'HK$',
  'HKD': 'HK$',
  'usd': 'US$',
  'USD': 'US$',

  // account
  'my_account': '我的帐户',
  'personal_information': '个人资讯',
  'billing_information': '帐单资讯',
  'billing_information_hint': '定价及当前计划',
  'no_billing': '没有帐单',

  // wallet
  'my_wallet': '我的电子钱包',
  'wallet': '电子钱包',
  'add_card': '新增信用卡',
  'remove_card': '移除信用卡',
  'default_card': '默认卡',
  'save_default_card': '保存为默认卡',
  'set_as_default': '设置为默认卡',
  'expiration_date': '到期日',
  'set_default_card_confirm': '你是否确定要把此卡设定为默认卡？',
  'set_default_card_hint': '默认卡将会在续订时自动收费',
  'remove_card_failed': '不能移除此卡，如你未曾退订，必须至少保留一张信用卡',
  'my_wallet_hint': '信用卡及付款方法',

  // course-rating
  'ratings&comments': '评分及评论',
  'course_review': '课程评论',
  'out_of': '满分为',
  'edit_course_review': '更改课程评论',
  'click_star_to_rate': '按下星星来评分',
  'allow_user_edit': '允许用户修改',
  'ratings': '评分',
  'comment': '评论',

  // learning-map
  'learning_map': '学习地图',
  'learning_map_template': '学习地图范本',
  'create_learning_map_template': '新增学习地图范本',
  'edit_learning_map_template': '编辑学习地图范本',
  'edit_template': '编辑范本',
  'more': '更多',

  'published_courses_count': '已发布课程数量',
  'delete_learning_map_prompt': '你是否确定要删除学习地图',
  'delete_learning_map_desc': '有关此学习地图的所有资料(包括已提交的资料)将会被删除',
  'cannot_delete_learning_map': '不能删除已发布的学习地图',
  'unpublish_learning_map_prompt': '你是否确定取消发布此学习地图？',
  'publish_learning_map_prompt': '你是否确定发布此学习地图？',

  'course_pool': '课程库',
  'with_order': '依序排列',
  'finish_each_day': '需要每天完成',
  'finish_each_day_hint': '当用户未按时完成时将发送提醒',
  'num_of_courses': '课程数量',
  'no_course_selected': '未选择课程',
  'not_yet_select_course_hint': '有一些课程尚未选定',
  'confirm_edit_learning_map': '你是否确定要更改此学习地图?',
  'edit_learning_map_hint': '有关此学习地图的所有资料(包括已提交的资料)将会被重置',
  'less_course_hint': '你所输入的课程数量少于现时已选择的课程数量',
  'confirm_reselect_course': '你是否确定重新选择全部课程?',
  'select_certificate': '请选择证书',
  'learning_map_report': '学习地图报告',
  'assigned_user': '已分配用户',
  'course_selected': '已选择课程',
  'remove_course': '移除课程',

  'assign_users': '分配用户',
  'assign_users_prompt': '你是否确定分配用户到此学习地图？',
  'unassign_users_prompt': '你是否确定要删除已分配用户?',
  'learning_map_assign_users': '学习地图分配用户',
  'learning_map_assign_users_template': '学习地图分配用户Excel范本',
  'user_list': '用户列表',
  'assigned_permissions': '已分配权限',

  'select_courses': '选择课程',
  'loading': '加载中',

  // certificate template
  'copy_certificate_template': '你是否确定要复制证书范本',
  'delete_certificate_template': '你是否确定要删除证书范本',
  'create_certificate_template': '新增证书范本',
  'edit_certificate_template': '编辑证书范本',
  'orientation': '方向',
  'landscape': '横向',
  'portrait': '纵向',
  'background_color': '背景颜色',
  'select_image': '选择图片',
  'subject_name': '学系名称',
  'theme_name': '主题名称',
  'certificate_no': '证书编号',
  'user_address': '用户地址',
  'edit_certificate_template_clear': '你是否确定要清空证书?',
  'certificate_regenerate': '重新生成证书',
  'certificate_preview': '预览证书',
  'certificate_clear': '清空证书',
  'add_content': '新增內容',
  'certificate_template': '证书范本',
  'course_name_en': '课程名称 (英语)',
  'course_name_zh_hk': '课程名称 (繁体中文)',
  'course_name_zh_cn': '课程名称 (简体中文)',
  'subject_name_en': '学系名称 (英语)',
  'subject_name_zh_hk': '学系名称 (繁体中文)',
  'subject_name_zh_cn': '学系名称 (简体中文)',
  'theme_name_en': '主题名称 (英语)',
  'theme_name_zh_hk': '主题名称 (繁体中文)',
  'theme_name_zh_cn': '主题名称 (简体中文)',
  'select_cert_temp':'选择证书范本',
  'no_cert_temp_selected': '未选择证书范本',


  // login
  'login_user_id_hint': '请输入您的用户编号',
  'login_password_hint': '请输入您的密码',
  'show_password': '显示密码',
  'hide_password': '隐藏密码',

  'batch_actions': '批量操作',

  // notification
  'push_notification': '推送通知',
  'push_notification_management': '推送通知管理',
  'course_notification': '课程通知',
  'notice': '通告',
  'push_time': '推送时间',
  'send_failed': '发送失败',
  'waiting_to_send': '等候发送',
  'pause': '暂停发送',

};
